#include "StdAfx.h"
#include "GameType.h"
#include "Packet.h"
#include "../GameLib/ItemData.h"

std::string g_strResourcePath = "d:/ymir work/";
std::string g_strImagePath = "d:/ymir work/ui/";

std::string g_strGuildSymbolPathName = "mark/10/";

// DEFAULT_FONT
static std::string gs_strDefaultFontName = "굴림체:12.fnt";
static std::string gs_strDefaultItalicFontName = "굴림체:12i.fnt";
static CResource* gs_pkDefaultFont = NULL;
static CResource* gs_pkDefaultItalicFont = NULL;

static bool gs_isReloadDefaultFont = false;

void DefaultFont_Startup()
{
	gs_pkDefaultFont = NULL;
}

void DefaultFont_Cleanup()
{
	if (gs_pkDefaultFont)
		gs_pkDefaultFont->Release();
}

void DefaultFont_SetName(const char * c_szFontName)
{
	gs_strDefaultFontName = c_szFontName;
	gs_strDefaultFontName += ".fnt";

	gs_strDefaultItalicFontName = c_szFontName;
	if(strchr(c_szFontName, ':'))
		gs_strDefaultItalicFontName += "i";
	gs_strDefaultItalicFontName += ".fnt";

	gs_isReloadDefaultFont = true;
}

bool ReloadDefaultFonts()
{
	CResourceManager& rkResMgr = CResourceManager::Instance();

	gs_isReloadDefaultFont = false;

	CResource* pkNewFont = rkResMgr.GetResourcePointer(gs_strDefaultFontName.c_str());
	pkNewFont->AddReference();
	if (gs_pkDefaultFont)
		gs_pkDefaultFont->Release();
	gs_pkDefaultFont = pkNewFont;

	CResource* pkNewItalicFont = rkResMgr.GetResourcePointer(gs_strDefaultItalicFontName.c_str());
	pkNewItalicFont->AddReference();
	if (gs_pkDefaultItalicFont)
		gs_pkDefaultItalicFont->Release();
	gs_pkDefaultItalicFont = pkNewItalicFont;

	return true;
}

CResource* DefaultFont_GetResource()
{
	if (!gs_pkDefaultFont || gs_isReloadDefaultFont)
		ReloadDefaultFonts();
	return gs_pkDefaultFont;
}

CResource* DefaultItalicFont_GetResource()
{
	if (!gs_pkDefaultItalicFont || gs_isReloadDefaultFont)
		ReloadDefaultFonts();
	return gs_pkDefaultItalicFont;
}

// END_OF_DEFAULT_FONT

void SetGuildSymbolPath(const char * c_szPathName)
{
	g_strGuildSymbolPathName = "mark/";
	g_strGuildSymbolPathName += c_szPathName;
	g_strGuildSymbolPathName += "/";
}

const char * GetGuildSymbolFileName(DWORD dwGuildID)
{
	return _getf("%s%03d.jpg", g_strGuildSymbolPathName.c_str(), dwGuildID);
}

BYTE c_aSlotTypeToInvenType[SLOT_TYPE_MAX] =
{
	RESERVED_WINDOW,		// SLOT_TYPE_NONE
	INVENTORY,				// SLOT_TYPE_INVENTORY
	RESERVED_WINDOW,		// SLOT_TYPE_SKILL
	RESERVED_WINDOW,		// SLOT_TYPE_EMOTION
	RESERVED_WINDOW,		// SLOT_TYPE_SHOP
	RESERVED_WINDOW,		// SLOT_TYPE_EXCHANGE_OWNER
	RESERVED_WINDOW,		// SLOT_TYPE_EXCHANGE_TARGET
	RESERVED_WINDOW,		// SLOT_TYPE_QUICK_SLOT
	RESERVED_WINDOW,		// SLOT_TYPE_SAFEBOX	<- SAFEBOX, MALL의 경우 하드 코딩되어있는 LEGACY 코드를 유지함.
	RESERVED_WINDOW,		// SLOT_TYPE_PRIVATE_SHOP
	RESERVED_WINDOW,		// SLOT_TYPE_MALL		<- SAFEBOX, MALL의 경우 하드 코딩되어있는 LEGACY 코드를 유지함.
	DRAGON_SOUL_INVENTORY,	// SLOT_TYPE_DRAGON_SOUL_INVENTORY
#ifdef ENABLE_SPECIAL_STORAGE
	UPGRADE_INVENTORY,
	BOOK_INVENTORY,
	STONE_INVENTORY,
	CHANGE_INVENTORY,
	COSTUME_INVENTORY,
	CHEST_INVENTORY,
#endif
#ifdef ENABLE_SWITCHBOT_WORLDARD
	SWITCHBOT,
#endif
#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
#endif
#ifdef CHANGE_EQUIP_WORLDARD
	CHANGE_EQUIP,
#endif
#if defined(ENABLE_AUTOMATIC_HUNTING_SYSTEM)
	RESERVED_WINDOW, // SLOT_TYPE_AUTO
#endif
#ifdef ENABLE_AURA_SYSTEM
	AURA_REFINE,			// SLOT_TYPE_AURA
#endif
};

BYTE SlotTypeToInvenType(BYTE bSlotType)
{
	if (bSlotType >= SLOT_TYPE_MAX)
		return RESERVED_WINDOW;
	else
		return c_aSlotTypeToInvenType[bSlotType];
}

static std::map<BYTE, BYTE> s_mapApplyToPoint
{
//	{ CItemData::APPLY_NONE, POINT_NONE }
	{ CItemData::APPLY_MAX_HP, POINT_MAX_HP }
	, { CItemData::APPLY_MAX_SP, POINT_MAX_SP }
	, { CItemData::APPLY_CON, POINT_HT }
	, { CItemData::APPLY_INT, POINT_IQ }
	, { CItemData::APPLY_STR, POINT_ST }
	, { CItemData::APPLY_DEX, POINT_DX }
	, { CItemData::APPLY_ATT_SPEED, POINT_ATT_SPEED }
	, { CItemData::APPLY_MOV_SPEED, POINT_MOV_SPEED }
	, { CItemData::APPLY_CAST_SPEED, POINT_CASTING_SPEED }
	, { CItemData::APPLY_HP_REGEN, POINT_HP_REGEN }
	, { CItemData::APPLY_SP_REGEN, POINT_SP_REGEN }
	, { CItemData::APPLY_POISON_PCT, POINT_POISON_PCT }
	, { CItemData::APPLY_STUN_PCT, POINT_STUN_PCT }
	, { CItemData::APPLY_SLOW_PCT, POINT_SLOW_PCT }
	, { CItemData::APPLY_CRITICAL_PCT, POINT_CRITICAL_PCT }
	, { CItemData::APPLY_PENETRATE_PCT, POINT_PENETRATE_PCT }
	, { CItemData::APPLY_ATTBONUS_HUMAN, POINT_ATTBONUS_HUMAN }
	, { CItemData::APPLY_ATTBONUS_ANIMAL, POINT_ATTBONUS_ANIMAL }
	, { CItemData::APPLY_ATTBONUS_ORC, POINT_ATTBONUS_ORC }
	, { CItemData::APPLY_ATTBONUS_MILGYO, POINT_ATTBONUS_MILGYO }
	, { CItemData::APPLY_ATTBONUS_UNDEAD, POINT_ATTBONUS_UNDEAD }
	, { CItemData::APPLY_ATTBONUS_DEVIL, POINT_ATTBONUS_DEVIL }
	, { CItemData::APPLY_STEAL_HP, POINT_STEAL_HP }
	, { CItemData::APPLY_STEAL_SP, POINT_STEAL_SP }
	, { CItemData::APPLY_MANA_BURN_PCT, POINT_MANA_BURN_PCT }
	, { CItemData::APPLY_DAMAGE_SP_RECOVER, POINT_DAMAGE_SP_RECOVER }
	, { CItemData::APPLY_BLOCK, POINT_BLOCK }
	, { CItemData::APPLY_DODGE, POINT_DODGE }
	, { CItemData::APPLY_RESIST_SWORD, POINT_RESIST_SWORD }
	, { CItemData::APPLY_RESIST_TWOHAND, POINT_RESIST_TWOHAND }
	, { CItemData::APPLY_RESIST_DAGGER, POINT_RESIST_DAGGER }
	, { CItemData::APPLY_RESIST_BELL, POINT_RESIST_BELL }
	, { CItemData::APPLY_RESIST_FAN, POINT_RESIST_FAN }
	, { CItemData::APPLY_RESIST_BOW, POINT_RESIST_BOW }
	, { CItemData::APPLY_RESIST_FIRE, POINT_RESIST_FIRE }
	, { CItemData::APPLY_RESIST_ELEC, POINT_RESIST_ELEC }
	, { CItemData::APPLY_RESIST_MAGIC, POINT_RESIST_MAGIC }
	, { CItemData::APPLY_RESIST_WIND, POINT_RESIST_WIND }
	, { CItemData::APPLY_REFLECT_MELEE, POINT_REFLECT_MELEE }
	, { CItemData::APPLY_REFLECT_CURSE, POINT_REFLECT_CURSE }
	, { CItemData::APPLY_POISON_REDUCE, POINT_POISON_REDUCE }
	, { CItemData::APPLY_KILL_SP_RECOVER, POINT_KILL_SP_RECOVER }
	, { CItemData::APPLY_EXP_DOUBLE_BONUS, POINT_EXP_DOUBLE_BONUS }
	, { CItemData::APPLY_GOLD_DOUBLE_BONUS, POINT_GOLD_DOUBLE_BONUS }
	, { CItemData::APPLY_ITEM_DROP_BONUS, POINT_ITEM_DROP_BONUS }
	, { CItemData::APPLY_POTION_BONUS, POINT_POTION_BONUS }
	, { CItemData::APPLY_KILL_HP_RECOVER, POINT_KILL_HP_RECOVERY }
	, { CItemData::APPLY_IMMUNE_STUN, POINT_IMMUNE_STUN }
	, { CItemData::APPLY_IMMUNE_SLOW, POINT_IMMUNE_SLOW }
	, { CItemData::APPLY_IMMUNE_FALL, POINT_IMMUNE_FALL }
//	, { CItemData::APPLY_SKILL, POINT_NONE }
	, { CItemData::APPLY_BOW_DISTANCE, POINT_BOW_DISTANCE }
	, { CItemData::APPLY_ATT_GRADE_BONUS, POINT_ATT_GRADE_BONUS }
	, { CItemData::APPLY_DEF_GRADE_BONUS, POINT_DEF_GRADE_BONUS }
	, { CItemData::APPLY_MAGIC_ATT_GRADE, POINT_MAGIC_ATT_GRADE_BONUS }
	, { CItemData::APPLY_MAGIC_DEF_GRADE, POINT_MAGIC_DEF_GRADE_BONUS }
	, { CItemData::APPLY_CURSE_PCT, POINT_CURSE_PCT }
	, { CItemData::APPLY_MAX_STAMINA, POINT_MAX_STAMINA }
	, { CItemData::APPLY_ATT_BONUS_TO_WARRIOR, POINT_ATTBONUS_WARRIOR }
	, { CItemData::APPLY_ATT_BONUS_TO_ASSASSIN, POINT_ATTBONUS_ASSASSIN }
	, { CItemData::APPLY_ATT_BONUS_TO_SURA, POINT_ATTBONUS_SURA }
	, { CItemData::APPLY_ATT_BONUS_TO_SHAMAN, POINT_ATTBONUS_SHAMAN }
	, { CItemData::APPLY_ATT_BONUS_TO_MONSTER, POINT_ATTBONUS_MONSTER }
	, { CItemData::APPLY_MALL_ATTBONUS, POINT_ATT_BONUS }
	, { CItemData::APPLY_MALL_DEFBONUS, POINT_MALL_DEFBONUS }
	, { CItemData::APPLY_MALL_EXPBONUS, POINT_MALL_EXPBONUS }
	, { CItemData::APPLY_MALL_ITEMBONUS, POINT_MALL_ITEMBONUS }
	, { CItemData::APPLY_MALL_GOLDBONUS, POINT_MALL_GOLDBONUS }
	, { CItemData::APPLY_MAX_HP_PCT, POINT_MAX_HP_PCT }
	, { CItemData::APPLY_MAX_SP_PCT, POINT_MAX_SP_PCT }
	, { CItemData::APPLY_SKILL_DAMAGE_BONUS, POINT_SKILL_DAMAGE_BONUS }
	, { CItemData::APPLY_NORMAL_HIT_DAMAGE_BONUS, POINT_NORMAL_HIT_DAMAGE_BONUS }
	, { CItemData::APPLY_SKILL_DEFEND_BONUS, POINT_SKILL_DEFEND_BONUS }
	, { CItemData::APPLY_NORMAL_HIT_DEFEND_BONUS, POINT_NORMAL_HIT_DEFEND_BONUS }
	, { CItemData::APPLY_PC_BANG_EXP_BONUS, POINT_PC_BANG_EXP_BONUS }
	, { CItemData::APPLY_PC_BANG_DROP_BONUS, POINT_PC_BANG_DROP_BONUS }
//	, { CItemData::APPLY_EXTRACT_HP_PCT, POINT_NONE }
	, { CItemData::APPLY_RESIST_WARRIOR, POINT_RESIST_WARRIOR }
	, { CItemData::APPLY_RESIST_ASSASSIN, POINT_RESIST_ASSASSIN }
	, { CItemData::APPLY_RESIST_SURA, POINT_RESIST_SURA }
	, { CItemData::APPLY_RESIST_SHAMAN, POINT_RESIST_SHAMAN }
	, { CItemData::APPLY_ENERGY, POINT_ENERGY }
	, { CItemData::APPLY_DEF_GRADE, POINT_DEF_GRADE }
	, { CItemData::APPLY_COSTUME_ATTR_BONUS, POINT_COSTUME_ATTR_BONUS }
	, { CItemData::APPLY_MAGIC_ATTBONUS_PER, POINT_MAGIC_ATT_BONUS_PER }
	, { CItemData::APPLY_MELEE_MAGIC_ATTBONUS_PER, POINT_MELEE_MAGIC_ATT_BONUS_PER }
	, { CItemData::APPLY_RESIST_ICE, POINT_RESIST_ICE }
	, { CItemData::APPLY_RESIST_EARTH, POINT_RESIST_EARTH }
	, { CItemData::APPLY_RESIST_DARK, POINT_RESIST_DARK }
	, { CItemData::APPLY_ANTI_CRITICAL_PCT, POINT_RESIST_CRITICAL }
	, { CItemData::APPLY_ANTI_PENETRATE_PCT, POINT_RESIST_PENETRATE }
#ifdef ENABLE_WOLFMAN_CHARACTER
	, { CItemData::APPLY_BLEEDING_REDUCE, POINT_BLEEDING_REDUCE }
	, { CItemData::APPLY_BLEEDING_PCT, POINT_BLEEDING_PCT }
	, { CItemData::APPLY_ATT_BONUS_TO_WOLFMAN, POINT_ATTBONUS_WOLFMAN }
	, { CItemData::APPLY_RESIST_WOLFMAN, POINT_RESIST_WOLFMAN }
	, { CItemData::APPLY_RESIST_CLAW, POINT_RESIST_CLAW }
#endif
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	, { CItemData::APPLY_ACCEDRAIN_RATE, POINT_ACCEDRAIN_RATE }
#endif
#ifdef ENABLE_MAGIC_REDUCTION_SYSTEM
	, { CItemData::APPLY_RESIST_MAGIC_REDUCTION, POINT_RESIST_MAGIC_REDUCTION }
#endif
//#ifdef ENABLE_NEW_BONUS_WORLDARD
//	, { CItemData::APPLY_RESIST_HUMAN, POINT_NONE }
//#endif
#ifdef ELEMENT_NEW_BONUSES
	, { CItemData::APPLY_ATTBONUS_ELEC, POINT_ATTBONUS_ELEC }
	, { CItemData::APPLY_ATTBONUS_FIRE, POINT_ATTBONUS_FIRE }
	, { CItemData::APPLY_ATTBONUS_ICE, POINT_ATTBONUS_ICE }
	, { CItemData::APPLY_ATTBONUS_WIND, POINT_ATTBONUS_WIND }
	, { CItemData::APPLY_ATTBONUS_EARTH, POINT_ATTBONUS_EARTH }
	, { CItemData::APPLY_ATTBONUS_DARK, POINT_ATTBONUS_DARK }
#endif
#ifdef ENABLE_YOHARA_SYSTEM
//	, { CItemData::APPLY_RANDOM, POINT_NONE }
	, { CItemData::APPLY_SUNGMA_STR, POINT_SUNGMA_STR }
	, { CItemData::APPLY_SUNGMA_HP, POINT_SUNGMA_HP }
	, { CItemData::APPLY_SUNGMA_MOVE, POINT_SUNGMA_MOVE }
	, { CItemData::APPLY_SUNGMA_IMMUNE, POINT_SUNGMA_IMMUNE }
#endif
#ifdef ELEMENT_NEW_BONUSES
	, { CItemData::APPLY_ENCHANT_ELEC, POINT_ENCHANT_ELEC }
	, { CItemData::APPLY_ENCHANT_FIRE, POINT_ENCHANT_FIRE }
	, { CItemData::APPLY_ENCHANT_ICE, POINT_ENCHANT_ICE }
	, { CItemData::APPLY_ENCHANT_WIND, POINT_ENCHANT_WIND }
	, { CItemData::APPLY_ENCHANT_EARTH, POINT_ENCHANT_EARTH }
	, { CItemData::APPLY_ENCHANT_DARK, POINT_ENCHANT_DARK }
	, { CItemData::APPLY_ATTBONUS_SWORD, POINT_ATTBONUS_SWORD }
	, { CItemData::APPLY_ATTBONUS_TWOHAND, POINT_ATTBONUS_TWOHAND }
	, { CItemData::APPLY_ATTBONUS_DAGGER, POINT_ATTBONUS_DAGGER }
	, { CItemData::APPLY_ATTBONUS_BELL, POINT_ATTBONUS_BELL }
	, { CItemData::APPLY_ATTBONUS_FAN, POINT_ATTBONUS_FAN }
	, { CItemData::APPLY_ATTBONUS_BOW, POINT_ATTBONUS_BOW }
	, { CItemData::APPLY_ATTBONUS_ZODIAC, POINT_ATTBONUS_ZODIAC }
	, { CItemData::APPLY_ATTBONUS_DESERT, POINT_ATTBONUS_DESERT }
	, { CItemData::APPLY_ATTBONUS_INSECT, POINT_ATTBONUS_INSECT }
#ifdef ENABLE_WOLFMAN_CHARACTER
	, { CItemData::APPLY_ATTBONUS_CLAW, POINT_ATTBONUS_CLAW }
#endif
#endif
#ifdef NEW_BONUS
	, { CItemData::APPLY_ATTBONUS_STONE, POINT_ATTBONUS_STONE }
	, { CItemData::APPLY_ATTBONUS_BOSS, POINT_ATTBONUS_BOSS }
#endif
#ifdef ENABLE_YOHARA_SYSTEM
	, { CItemData::APPLY_HIT_PCT, POINT_HIT_PCT }
	, { CItemData::APPLY_RESIST_MOUNT_FALL, POINT_RESIST_MOUNT_FALL }
	, { CItemData::APPLY_MONSTER_DEFEND_BONUS, POINT_MONSTER_DEFEND_BONUS }
#endif
// #ifdef USE_DROP_AFFECT_BONUSES
	, { CItemData::APPLY_DOUBLE_DROP_METIN, POINT_DOUBLE_DROP_METIN }
	, { CItemData::APPLY_DOUBLE_DROP_BOSS, POINT_DOUBLE_DROP_BOSS }
// #endif
};

BYTE ApplyTypeToPointType(BYTE bType)
{
	const auto it = s_mapApplyToPoint.find(bType);
	return it != s_mapApplyToPoint.end() ? it->second : POINT_NONE;
}

static std::map<BYTE, BYTE> s_mapPointToApply
{
//	{ CItemData::APPLY_NONE, CItemData::APPLY_NONE }
	{ POINT_MAX_HP, CItemData::APPLY_MAX_HP }
	, { POINT_MAX_SP, CItemData::APPLY_MAX_SP }
	, { POINT_HT, CItemData::APPLY_CON }
	, { POINT_IQ, CItemData::APPLY_INT }
	, { POINT_ST, CItemData::APPLY_STR }
	, { POINT_DX, CItemData::APPLY_DEX }
	, { POINT_ATT_SPEED, CItemData::APPLY_ATT_SPEED }
	, { POINT_MOV_SPEED, CItemData::APPLY_MOV_SPEED }
	, { POINT_CASTING_SPEED, CItemData::APPLY_CAST_SPEED }
	, { POINT_HP_REGEN, CItemData::APPLY_HP_REGEN }
	, { POINT_SP_REGEN, CItemData::APPLY_SP_REGEN }
	, { POINT_POISON_PCT, CItemData::APPLY_POISON_PCT }
	, { POINT_STUN_PCT, CItemData::APPLY_STUN_PCT }
	, { POINT_SLOW_PCT, CItemData::APPLY_SLOW_PCT }
	, { POINT_CRITICAL_PCT, CItemData::APPLY_CRITICAL_PCT }
	, { POINT_PENETRATE_PCT, CItemData::APPLY_PENETRATE_PCT }
	, { POINT_ATTBONUS_HUMAN, CItemData::APPLY_ATTBONUS_HUMAN }
	, { POINT_ATTBONUS_ANIMAL, CItemData::APPLY_ATTBONUS_ANIMAL }
	, { POINT_ATTBONUS_ORC, CItemData::APPLY_ATTBONUS_ORC }
	, { POINT_ATTBONUS_MILGYO, CItemData::APPLY_ATTBONUS_MILGYO }
	, { POINT_ATTBONUS_UNDEAD, CItemData::APPLY_ATTBONUS_UNDEAD }
	, { POINT_ATTBONUS_DEVIL, CItemData::APPLY_ATTBONUS_DEVIL }
	, { POINT_STEAL_HP, CItemData::APPLY_STEAL_HP }
	, { POINT_STEAL_SP, CItemData::APPLY_STEAL_SP }
	, { POINT_MANA_BURN_PCT, CItemData::APPLY_MANA_BURN_PCT }
	, { POINT_DAMAGE_SP_RECOVER, CItemData::APPLY_DAMAGE_SP_RECOVER }
	, { POINT_BLOCK, CItemData::APPLY_BLOCK }
	, { POINT_DODGE, CItemData::APPLY_DODGE }
	, { POINT_RESIST_SWORD, CItemData::APPLY_RESIST_SWORD }
	, { POINT_RESIST_TWOHAND, CItemData::APPLY_RESIST_TWOHAND }
	, { POINT_RESIST_DAGGER, CItemData::APPLY_RESIST_DAGGER }
	, { POINT_RESIST_BELL, CItemData::APPLY_RESIST_BELL }
	, { POINT_RESIST_FAN, CItemData::APPLY_RESIST_FAN }
	, { POINT_RESIST_BOW, CItemData::APPLY_RESIST_BOW }
	, { POINT_RESIST_FIRE, CItemData::APPLY_RESIST_FIRE }
	, { POINT_RESIST_ELEC, CItemData::APPLY_RESIST_ELEC }
	, { POINT_RESIST_MAGIC, CItemData::APPLY_RESIST_MAGIC }
	, { POINT_RESIST_WIND, CItemData::APPLY_RESIST_WIND }
	, { POINT_REFLECT_MELEE, CItemData::APPLY_REFLECT_MELEE }
	, { POINT_REFLECT_CURSE, CItemData::APPLY_REFLECT_CURSE }
	, { POINT_POISON_REDUCE, CItemData::APPLY_POISON_REDUCE }
	, { POINT_KILL_SP_RECOVER, CItemData::APPLY_KILL_SP_RECOVER }
	, { POINT_EXP_DOUBLE_BONUS, CItemData::APPLY_EXP_DOUBLE_BONUS }
	, { POINT_GOLD_DOUBLE_BONUS, CItemData::APPLY_GOLD_DOUBLE_BONUS }
	, { POINT_ITEM_DROP_BONUS, CItemData::APPLY_ITEM_DROP_BONUS }
	, { POINT_POTION_BONUS, CItemData::APPLY_POTION_BONUS }
	, { POINT_KILL_HP_RECOVERY, CItemData::APPLY_KILL_HP_RECOVER }
	, { POINT_IMMUNE_STUN, CItemData::APPLY_IMMUNE_STUN }
	, { POINT_IMMUNE_SLOW, CItemData::APPLY_IMMUNE_SLOW }
	, { POINT_IMMUNE_FALL, CItemData::APPLY_IMMUNE_FALL }
//	, { POINT_NONE, CItemData::APPLY_SKILL }
	, { POINT_BOW_DISTANCE, CItemData::APPLY_BOW_DISTANCE }
	, { POINT_ATT_GRADE_BONUS, CItemData::APPLY_ATT_GRADE_BONUS }
	, { POINT_DEF_GRADE_BONUS, CItemData::APPLY_DEF_GRADE_BONUS }
	, { POINT_MAGIC_ATT_GRADE_BONUS, CItemData::APPLY_MAGIC_ATT_GRADE }
	, { POINT_MAGIC_DEF_GRADE_BONUS, CItemData::APPLY_MAGIC_DEF_GRADE }
	, { POINT_CURSE_PCT, CItemData::APPLY_CURSE_PCT }
	, { POINT_MAX_STAMINA, CItemData::APPLY_MAX_STAMINA }
	, { POINT_ATTBONUS_WARRIOR, CItemData::APPLY_ATT_BONUS_TO_WARRIOR }
	, { POINT_ATTBONUS_ASSASSIN, CItemData::APPLY_ATT_BONUS_TO_ASSASSIN }
	, { POINT_ATTBONUS_SURA, CItemData::APPLY_ATT_BONUS_TO_SURA }
	, { POINT_ATTBONUS_SHAMAN, CItemData::APPLY_ATT_BONUS_TO_SHAMAN }
	, { POINT_ATTBONUS_MONSTER, CItemData::APPLY_ATT_BONUS_TO_MONSTER }
	, { POINT_ATT_BONUS, CItemData::APPLY_MALL_ATTBONUS }
	, { POINT_MALL_DEFBONUS, CItemData::APPLY_MALL_DEFBONUS }
	, { POINT_MALL_EXPBONUS, CItemData::APPLY_MALL_EXPBONUS }
	, { POINT_MALL_ITEMBONUS, CItemData::APPLY_MALL_ITEMBONUS }
	, { POINT_MALL_GOLDBONUS, CItemData::APPLY_MALL_GOLDBONUS }
	, { POINT_MAX_HP_PCT, CItemData::APPLY_MAX_HP_PCT }
	, { POINT_MAX_SP_PCT, CItemData::APPLY_MAX_SP_PCT }
	, { POINT_SKILL_DAMAGE_BONUS, CItemData::APPLY_SKILL_DAMAGE_BONUS }
	, { POINT_NORMAL_HIT_DAMAGE_BONUS, CItemData::APPLY_NORMAL_HIT_DAMAGE_BONUS }
	, { POINT_SKILL_DEFEND_BONUS, CItemData::APPLY_SKILL_DEFEND_BONUS }
	, { POINT_NORMAL_HIT_DEFEND_BONUS, CItemData::APPLY_NORMAL_HIT_DEFEND_BONUS }
	, { POINT_PC_BANG_EXP_BONUS, CItemData::APPLY_PC_BANG_EXP_BONUS }
	, { POINT_PC_BANG_DROP_BONUS, CItemData::APPLY_PC_BANG_DROP_BONUS }
//	, { POINT_NONE, CItemData::APPLY_EXTRACT_HP_PCT }
	, { POINT_RESIST_WARRIOR, CItemData::APPLY_RESIST_WARRIOR }
	, { POINT_RESIST_ASSASSIN, CItemData::APPLY_RESIST_ASSASSIN }
	, { POINT_RESIST_SURA, CItemData::APPLY_RESIST_SURA }
	, { POINT_RESIST_SHAMAN, CItemData::APPLY_RESIST_SHAMAN }
	, { POINT_ENERGY, CItemData::APPLY_ENERGY }
	, { POINT_DEF_GRADE, CItemData::APPLY_DEF_GRADE }
	, { POINT_COSTUME_ATTR_BONUS, CItemData::APPLY_COSTUME_ATTR_BONUS }
	, { POINT_MAGIC_ATT_BONUS_PER, CItemData::APPLY_MAGIC_ATTBONUS_PER }
	, { POINT_MELEE_MAGIC_ATT_BONUS_PER, CItemData::APPLY_MELEE_MAGIC_ATTBONUS_PER }
	, { POINT_RESIST_ICE, CItemData::APPLY_RESIST_ICE }
	, { POINT_RESIST_EARTH, CItemData::APPLY_RESIST_EARTH }
	, { POINT_RESIST_DARK, CItemData::APPLY_RESIST_DARK }
	, { POINT_RESIST_CRITICAL, CItemData::APPLY_ANTI_CRITICAL_PCT }
	, { POINT_RESIST_PENETRATE, CItemData::APPLY_ANTI_PENETRATE_PCT }
#ifdef ENABLE_WOLFMAN_CHARACTER
	, { POINT_BLEEDING_REDUCE, CItemData::APPLY_BLEEDING_REDUCE }
	, { POINT_BLEEDING_PCT, CItemData::APPLY_BLEEDING_PCT }
	, { POINT_ATTBONUS_WOLFMAN, CItemData::APPLY_ATT_BONUS_TO_WOLFMAN }
	, { POINT_RESIST_WOLFMAN, CItemData::APPLY_RESIST_WOLFMAN }
	, { POINT_RESIST_CLAW, CItemData::APPLY_RESIST_CLAW }
#endif
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	, { POINT_ACCEDRAIN_RATE, CItemData::APPLY_ACCEDRAIN_RATE }
#endif
#ifdef ENABLE_MAGIC_REDUCTION_SYSTEM
	, { POINT_RESIST_MAGIC_REDUCTION, CItemData::APPLY_RESIST_MAGIC_REDUCTION }
#endif
//#ifdef ENABLE_NEW_BONUS_WORLDARD
//	, { POINT_NONE, CItemData::APPLY_RESIST_HUMAN }
//#endif
#ifdef ELEMENT_NEW_BONUSES
	, { POINT_ATTBONUS_ELEC, CItemData::APPLY_ATTBONUS_ELEC }
	, { POINT_ATTBONUS_FIRE, CItemData::APPLY_ATTBONUS_FIRE }
	, { POINT_ATTBONUS_ICE, CItemData::APPLY_ATTBONUS_ICE }
	, { POINT_ATTBONUS_WIND, CItemData::APPLY_ATTBONUS_WIND }
	, { POINT_ATTBONUS_EARTH, CItemData::APPLY_ATTBONUS_EARTH }
	, { POINT_ATTBONUS_DARK, CItemData::APPLY_ATTBONUS_DARK }
#endif
#ifdef ENABLE_YOHARA_SYSTEM
//	, { POINT_NONE, CItemData::APPLY_RANDOM }
	, { POINT_SUNGMA_STR, CItemData::APPLY_SUNGMA_STR }
	, { POINT_SUNGMA_HP, CItemData::APPLY_SUNGMA_HP }
	, { POINT_SUNGMA_MOVE, CItemData::APPLY_SUNGMA_MOVE }
	, { POINT_SUNGMA_IMMUNE, CItemData::APPLY_SUNGMA_IMMUNE }
#endif
#ifdef ELEMENT_NEW_BONUSES
	, { POINT_ENCHANT_ELEC, CItemData::APPLY_ENCHANT_ELEC }
	, { POINT_ENCHANT_FIRE, CItemData::APPLY_ENCHANT_FIRE }
	, { POINT_ENCHANT_ICE, CItemData::APPLY_ENCHANT_ICE }
	, { POINT_ENCHANT_WIND, CItemData::APPLY_ENCHANT_WIND }
	, { POINT_ENCHANT_EARTH, CItemData::APPLY_ENCHANT_EARTH }
	, { POINT_ENCHANT_DARK, CItemData::APPLY_ENCHANT_DARK }
	, { POINT_ATTBONUS_SWORD, CItemData::APPLY_ATTBONUS_SWORD }
	, { POINT_ATTBONUS_TWOHAND, CItemData::APPLY_ATTBONUS_TWOHAND }
	, { POINT_ATTBONUS_DAGGER, CItemData::APPLY_ATTBONUS_DAGGER }
	, { POINT_ATTBONUS_BELL, CItemData::APPLY_ATTBONUS_BELL }
	, { POINT_ATTBONUS_FAN, CItemData::APPLY_ATTBONUS_FAN }
	, { POINT_ATTBONUS_BOW, CItemData::APPLY_ATTBONUS_BOW }
	, { POINT_ATTBONUS_ZODIAC, CItemData::APPLY_ATTBONUS_ZODIAC }
	, { POINT_ATTBONUS_DESERT, CItemData::APPLY_ATTBONUS_DESERT }
	, { POINT_ATTBONUS_INSECT, CItemData::APPLY_ATTBONUS_INSECT }
#ifdef ENABLE_WOLFMAN_CHARACTER
	, { POINT_ATTBONUS_CLAW, CItemData::APPLY_ATTBONUS_CLAW }
#endif
#endif
#ifdef NEW_BONUS
	, { POINT_ATTBONUS_STONE, CItemData::APPLY_ATTBONUS_STONE }
	, { POINT_ATTBONUS_BOSS, CItemData::APPLY_ATTBONUS_BOSS }
#endif
#ifdef ENABLE_YOHARA_SYSTEM
	, { POINT_HIT_PCT, CItemData::APPLY_HIT_PCT }
	, { POINT_RESIST_MOUNT_FALL, CItemData::APPLY_RESIST_MOUNT_FALL }
	, { POINT_MONSTER_DEFEND_BONUS, CItemData::APPLY_MONSTER_DEFEND_BONUS }
#endif
// #ifdef USE_DROP_AFFECT_BONUSES
	, { POINT_DOUBLE_DROP_METIN, CItemData::APPLY_DOUBLE_DROP_METIN }
	, { POINT_DOUBLE_DROP_BOSS, CItemData::APPLY_DOUBLE_DROP_BOSS }
// #endif
// #ifdef USE_PREMIUM_AFFECT
	, { POINT_PREMIUM_USER, CItemData::APPLY_NONE }
// #endif
};

BYTE PointTypeToApplyType(BYTE bType)
{
	const auto it = s_mapPointToApply.find(bType);
	return it != s_mapPointToApply.end() ? it->second : CItemData::APPLY_NONE;
}

#ifdef ENABLE_AURA_SYSTEM
static int s_aiAuraRefineInfo[CItemData::AURA_GRADE_MAX_NUM][AURA_REFINE_INFO_MAX] = {
	{1,   1,  49,  1000, 30617, 20,  50000000, 100},
	{2,  50,  99,  2000, 30617, 50,  50000000, 100},
	{3, 100, 149,  4000, 30616, 20,  50000000, 100},
	{4, 150, 199,  8000, 30616, 40,  80000000, 100},
	{5, 200, 249, 16000, 30618, 40, 100000000, 100},
	{6, 250, 250,     0,     0,  0,        0,   0},
	{0,   0,   0,     0,     0,  0,        0,   0}
};

int* GetAuraRefineInfo(BYTE bLevel)
{
	if (bLevel > 250)
		return NULL;

	for (int i = 0; i < CItemData::AURA_GRADE_MAX_NUM + 1; ++i)
	{
		if (bLevel >= s_aiAuraRefineInfo[i][AURA_REFINE_INFO_LEVEL_MIN] && bLevel <= s_aiAuraRefineInfo[i][AURA_REFINE_INFO_LEVEL_MAX])
			return s_aiAuraRefineInfo[i];
	}

	return NULL;
}
#endif
