#ifndef __INC_METIN2_ITEM_LENGTH_H__
#define __INC_METIN2_ITEM_LENGTH_H__

#include "CommonDefines.h"

enum EItemMisc
{
	ITEM_NAME_MAX_LEN			= 24,
	ITEM_VALUES_MAX_NUM			= 6,
	ITEM_SMALL_DESCR_MAX_LEN	= 256,
	ITEM_LIMIT_MAX_NUM			= 2,
	ITEM_APPLY_MAX_NUM			= 3,
	ITEM_SOCKET_MAX_NUM			= 8,//new socket max.
	//ITEM_MAX_COUNT				= 5000,//unused
	ITEM_STONES_MAX_NUM 		= 4,
#ifdef ENABLE_LOCK_ATTR
	LOCK_ATTR_DATA_INDEX		= 7,
#endif

	ITEM_ATTRIBUTE_NORM_START	= 0,
	ITEM_ATTRIBUTE_NORM_END		= ITEM_ATTRIBUTE_NORM_START + ITEM_ATTRIBUTE_NORM_NUM,

	ITEM_ATTRIBUTE_RARE_START	= ITEM_ATTRIBUTE_NORM_END,
	ITEM_ATTRIBUTE_RARE_END		= ITEM_ATTRIBUTE_RARE_START + ITEM_ATTRIBUTE_RARE_NUM,

	// MAX_NORM_ATTR_NUM			= 5,
	// MAX_RARE_ATTR_NUM			= 2,

	ITEM_ATTRIBUTE_MAX_NUM		= 15, // 7
#ifdef ENABLE_SWITCHBOT
	MAX_NORM_ATTR_NUM			= 5,
	MAX_RARE_ATTR_NUM			= 2,
#endif
	
#ifdef ENABLE_YOHARA_SYSTEM
	APPLY_RANDOM_SLOT_MAX_NUM = 3,
#endif

	ITEM_ATTRIBUTE_MAX_LEVEL	= 5,
	ITEM_AWARD_WHY_MAX_LEN		= 50,

	REFINE_MATERIAL_MAX_NUM		= 5,

	ITEM_ELK_VNUM				= 50026,
	
#ifdef ENABLE_PITTY_REFINE
	ITEM_VNUM_SEAL_OF_GOD		= 94910,
	EXTRA_CHANCE_SEAL_OF_GOD	= 5,
#endif

#if defined(ENABLE_SWITCHBOT) && defined(ENABLE_SWITCHBOT_RENEWAL)
	ITEM_VNUM_SWITCHBOT_PREMIUM = 50027,
#endif
};

const BYTE ITEM_SOCKET_REMAIN_SEC = 0;
enum EItemValueIdice
{
	ITEM_VALUE_DRAGON_SOUL_POLL_OUT_BONUS_IDX = 0,
	ITEM_VALUE_CHARGING_AMOUNT_IDX = 0,
	ITEM_VALUE_SECONDARY_COIN_UNIT_IDX = 0,
};
enum EItemDragonSoulSockets
{
	ITEM_SOCKET_DRAGON_SOUL_ACTIVE_IDX = 2,
	ITEM_SOCKET_CHARGING_AMOUNT_IDX = 2,
};
// Çæ ÀÌ°Å ¹ÌÄ£°Å ¾Æ´Ï¾ß?
// ³ªÁß¿¡ ¼ÒÄÏ È®ÀåÇÏ¸é ¾îÂ¼·Á°í ÀÌÁö¶ö -_-;;;
enum EItemUniqueSockets
{
	ITEM_SOCKET_UNIQUE_SAVE_TIME = ITEM_SOCKET_MAX_NUM - 2,
	ITEM_SOCKET_UNIQUE_REMAIN_TIME = ITEM_SOCKET_MAX_NUM - 1
};

enum EItemTypes
{
	ITEM_NONE,						// 0
	ITEM_WEAPON,					// 1
	ITEM_ARMOR,						// 2
	ITEM_USE,						// 3
	ITEM_AUTOUSE,					// 4
	ITEM_MATERIAL,					// 5
	ITEM_SPECIAL,					// 6
	ITEM_TOOL,						// 7
	ITEM_LOTTERY,					// 8
	ITEM_ELK,						// 9
	ITEM_METIN,						// 10
	ITEM_CONTAINER,					// 11
	ITEM_FISH,						// 12
	ITEM_ROD,						// 13
	ITEM_RESOURCE,					// 14
	ITEM_CAMPFIRE,					// 15
	ITEM_UNIQUE,					// 16
	ITEM_SKILLBOOK,					// 17
	ITEM_QUEST,						// 18
	ITEM_POLYMORPH,					// 19
	ITEM_TREASURE_BOX,				// 20
	ITEM_TREASURE_KEY,				// 21
	ITEM_SKILLFORGET,				// 22
	ITEM_GIFTBOX,					// 23
	ITEM_PICK,						// 24
	ITEM_HAIR,						// 25
	ITEM_TOTEM,						// 26
	ITEM_BLEND,						// 27
	ITEM_COSTUME,					// 28
	ITEM_DS,						// 29
	ITEM_SPECIAL_DS,				// 30
	ITEM_EXTRACT,					// 31
	ITEM_SECONDARY_COIN,			// 32
	ITEM_RING,						// 33
	ITEM_BELT,						// 34
//#ifdef __ITEM_SHINING__
	ITEM_SHINING,					// 35
//#endif
	ITEM_NEW_RINGS,					// 36
//#ifdef ENABLE_NEW_PET_SYSTEM
	ITEM_PET,						// 37
//#endif
//#ifdef __BUFFI_SUPPORT__
	ITEM_BUFFI,						// 38
//#endif
//#ifdef ENABLE_NEWEQ
	ITEM_NEWRING,					// 39
//#endif
	ITEM_RING_SPECIAL,				// 40
	ITEM_BOOSTER,					// 41
//#ifdef USE_CRYSTAL_SYSTEM
	ITEM_CRYSTAL,					// 42
//#endif
};

enum EBoosterSubTypes
{
	BOOSTER_HEAD,
	BOOSTER_ARMOR,
	BOOSTER_WEAPON,
};

enum EMetinSubTypes
{
	METIN_NORMAL,
	METIN_GOLD,
};

#ifdef __BUFFI_SUPPORT__
enum EBuffiSubTypes
{
	BUFFI_SCROLL,
	BUFFI_NAME_SCROLL,
};
#endif

enum EWeaponSubTypes
{
	WEAPON_SWORD,
	WEAPON_DAGGER,
	WEAPON_BOW,
	WEAPON_TWO_HANDED,
	WEAPON_BELL,
	WEAPON_FAN,
	WEAPON_ARROW,
	WEAPON_MOUNT_SPEAR,
#ifdef ENABLE_WOLFMAN_CHARACTER
	WEAPON_CLAW,
#endif
	WEAPON_QUIVER,
	WEAPON_NUM_TYPES,
};

enum EArmorSubTypes
{
	ARMOR_BODY,
	ARMOR_HEAD,
	ARMOR_SHIELD,
	ARMOR_WRIST,
	ARMOR_FOOTS,
	ARMOR_NECK,
	ARMOR_EAR,
#ifdef ENABLE_YOHARA_SYSTEM
	ARMOR_GLOVE,
#endif
	ARMOR_PENDANT_FIRE,
	ARMOR_PENDANT_ICE,
	ARMOR_PENDANT_THUNDER,
	ARMOR_PENDANT_WIND,
	ARMOR_PENDANT_EARTH,
	ARMOR_PENDANT_DARK,
	ARMOR_PENDANT_SOUL,
	ARMOR_NUM_TYPES
};

#ifdef __ITEM_SHINING__
enum EShiningSubTypes
{
	SHINING_WEAPON,
	SHINING_ARMOR,
	SHINING_SPECIAL,
};
#endif

enum ECostumeSubTypes
{
	COSTUME_BODY = ARMOR_BODY,			// [Áß¿ä!!] ECostumeSubTypes enum value´Â  Á¾·ùº°·Î EArmorSubTypesÀÇ ±×°Í°ú °°¾Æ¾ß ÇÔ.
	COSTUME_HAIR = ARMOR_HEAD,			// ÀÌ´Â ÄÚ½ºÃõ ¾ÆÀÌÅÛ¿¡ Ãß°¡ ¼Ó¼ºÀ» ºÙÀÌ°Ú´Ù´Â »ç¾÷ºÎÀÇ ¿äÃ»¿¡ µû¶ó¼­ ±âÁ¸ ·ÎÁ÷À» È°¿ëÇÏ±â À§ÇÔÀÓ.
#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	COSTUME_MOUNT	= 2,
#endif
#ifdef __SASH_SYSTEM__
	COSTUME_SASH	= 3,
#endif
#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	COSTUME_WEAPON	= 4,
#endif
#ifdef ENABLE_SASH_COSTUME_SYSTEM
	COSTUME_NEW_SASH	= 5,
#endif
#ifdef ENABLE_NEW_PET_SYSTEM
	COSTUME_PET = 6,
#endif
#ifdef ENABLE_MOUNT_SKIN
	COSTUME_MOUNT_SKIN = 7,
#endif
#ifdef __AURA_SYSTEM__
	COSTUME_AURA = 8,
#endif

	COSTUME_NUM_TYPES,
};

#ifdef ENABLE_NEW_PET_SYSTEM
enum EPetSubTypes
{
	PET_LEVELABLE,
	PET_EGG,
	PET_TRANSPORTBOX,
	PET_PROTEIN,
	PET_CHANGE_NAME_ITEM,
	PET_DEW,
	PET_SKILL,
	PET_PRIMIUM_FEEDSTUFF,
	PET_ATTR_CHANGE,
	PET_ATTR_DETERMINE,
	PET_EXPFOOD_PER,
	PET_SKILL_DEL_BOOK,
	PET_SKILL_ALL_DEL_BOOK,
	PET_EXPFOOD,
	PET_FEEDSTUFF,
};
#endif

enum EDragonSoulSubType
{
	DS_SLOT1,
	DS_SLOT2,
	DS_SLOT3,
	DS_SLOT4,
	DS_SLOT5,
	DS_SLOT6,
	DS_SLOT_MAX,
};

enum EDragonSoulGradeTypes
{
	DRAGON_SOUL_GRADE_NORMAL,
	DRAGON_SOUL_GRADE_BRILLIANT,
	DRAGON_SOUL_GRADE_RARE,
	DRAGON_SOUL_GRADE_ANCIENT,
	DRAGON_SOUL_GRADE_LEGENDARY,
#ifdef ENABLE_DS_GRADE_MYTH
	DRAGON_SOUL_GRADE_MYTH,
#endif
	DRAGON_SOUL_GRADE_MAX,

};

enum EDragonSoulStepTypes
{
	DRAGON_SOUL_STEP_LOWEST,
	DRAGON_SOUL_STEP_LOW,
	DRAGON_SOUL_STEP_MID,
	DRAGON_SOUL_STEP_HIGH,
	DRAGON_SOUL_STEP_HIGHEST,
	DRAGON_SOUL_STEP_MAX,
};
#define DRAGON_SOUL_STRENGTH_MAX 7

enum EDSInventoryMaxNum
{
	DRAGON_SOUL_INVENTORY_MAX_NUM = DS_SLOT_MAX * DRAGON_SOUL_GRADE_MAX * DRAGON_SOUL_BOX_SIZE,
};

enum EFishSubTypes
{
	FISH_ALIVE,
	FISH_DEAD,
};

enum EResourceSubTypes
{
	RESOURCE_FISHBONE,
	RESOURCE_WATERSTONEPIECE,
	RESOURCE_WATERSTONE,
	RESOURCE_BLOOD_PEARL,
	RESOURCE_BLUE_PEARL,
	RESOURCE_WHITE_PEARL,
	RESOURCE_BUCKET,
	RESOURCE_CRYSTAL,
	RESOURCE_GEM,
	RESOURCE_STONE,
	RESOURCE_METIN,
	RESOURCE_ORE,
#ifdef __AURA_SYSTEM__
	RESOURCE_AURA
#endif

};

enum EUniqueSubTypes
{
	UNIQUE_NONE,
	UNIQUE_BOOK,
	UNIQUE_SPECIAL_RIDE,
	UNIQUE_SPECIAL_MOUNT_RIDE,
};

#ifdef __AURA_SYSTEM__
enum EItemAuraSockets
{
	ITEM_SOCKET_AURA_DRAIN_ITEM_VNUM,
	ITEM_SOCKET_AURA_CURRENT_LEVEL,
	ITEM_SOCKET_AURA_BOOST,
};

enum EItemAuraMaterialValues
{
	ITEM_AURA_MATERIAL_EXP_VALUE,
};

enum EItemAuraBoostValues
{
	ITEM_AURA_BOOST_PERCENT_VALUE,
	ITEM_AURA_BOOST_TIME_VALUE,
	ITEM_AURA_BOOST_UNLIMITED_VALUE,
};

enum EItemAuraBoostIndex
{
	ITEM_AURA_BOOST_ERASER,
	ITEM_AURA_BOOST_WEAK,
	ITEM_AURA_BOOST_NORMAL,
	ITEM_AURA_BOOST_STRONG,
	ITEM_AURA_BOOST_ULTIMATE,
	ITEM_AURA_BOOST_MAX,
};
#endif

enum EExtractSubTypes
{
	EXTRACT_DRAGON_SOUL,
	EXTRACT_DRAGON_HEART,
};

enum EAutoUseSubTypes
{
	AUTOUSE_POTION,
	AUTOUSE_ABILITY_UP,
	AUTOUSE_BOMB,
	AUTOUSE_GOLD,
	AUTOUSE_MONEYBAG,
	AUTOUSE_TREASURE_BOX
};

enum EMaterialSubTypes
{
	MATERIAL_LEATHER,
	MATERIAL_BLOOD,
	MATERIAL_ROOT,
	MATERIAL_NEEDLE,
	MATERIAL_JEWEL,
	MATERIAL_DS_REFINE_NORMAL,
	MATERIAL_DS_REFINE_BLESSED,
	MATERIAL_DS_REFINE_HOLLY,
};

enum ESpecialSubTypes
{
	SPECIAL_MAP,
	SPECIAL_KEY,
	SPECIAL_DOC,
	SPECIAL_SPIRIT,
};

enum EToolSubTypes
{
	TOOL_FISHING_ROD
};

enum ELotterySubTypes
{
	LOTTERY_TICKET,
	LOTTERY_INSTANT
};

#ifdef ENABLE_NEWEQ
enum ENewRingSubTypes
{
	RING_SLOT1,
	RING_SLOT2,
	RING_SLOT3,
	RING_SLOT4,
	RING_SLOT5, //marriage 1
	RING_SLOT6,	//marriage 2
	RING_SLOT7,	//marriage 2
};
#endif

enum ESpecialRingSubTypes
{
	SPECIAL_RING_SLOT1,
	SPECIAL_RING_SLOT2,
};

enum EItemWearableFlag
{
	WEARABLE_BODY	= (1 << 0),
	WEARABLE_HEAD	= (1 << 1),
	WEARABLE_FOOTS	= (1 << 2),
	WEARABLE_WRIST	= (1 << 3),
	WEARABLE_WEAPON	= (1 << 4),
	WEARABLE_NECK	= (1 << 5),
	WEARABLE_EAR	= (1 << 6),
	WEARABLE_UNIQUE	= (1 << 7),
	WEARABLE_SHIELD	= (1 << 8),
	WEARABLE_ARROW	= (1 << 9),
	WEARABLE_HAIR	= (1 << 10),
	WEARABLE_ABILITY		= (1 << 11),
	WEARABLE_COSTUME_BODY	= (1 << 12),

#ifdef __SASH_SYSTEM__
	WEARABLE_COSTUME_SASH	= (1 << 14),
#endif
#ifdef ENABLE_SASH_COSTUME_SYSTEM
	WEARABLE_COSTUME_NEW_SASH	= (1 << 15),
#endif
#ifdef ENABLE_YOHARA_SYSTEM
	WEARABLE_GLOVE = (1 << 16),
#endif
#ifdef ITEM_TALISMAN_EQUIPMENT
	WEARABLE_PENDANT = (1 << 17),
#endif
#ifdef ENABLE_NEWEQ
	WEARABLE_NEW_RING = (1 << 18),
#endif
};

enum ELimitTypes
{
	LIMIT_NONE,
	LIMIT_LEVEL,
	LIMIT_STR,
	LIMIT_DEX,
	LIMIT_INT,
	LIMIT_CON,
	LIMIT_PCBANG,
	LIMIT_REAL_TIME,
	LIMIT_REAL_TIME_START_FIRST_USE,
	LIMIT_TIMER_BASED_ON_WEAR,
//#ifdef ENABLE_PITTY_REFINE
	LIMIT_PITTY_REFINE,
//#endif
//#ifdef ENABLE_YOHARA_SYSTEM
	LIMIT_CONQUEROR_LEVEL,
//#endif
	LIMIT_MAX_NUM
};

enum EAttrAddonTypes
{
	ATTR_ADDON_NONE,
	// positive values are reserved for set
	ATTR_DAMAGE_ADDON = -1,
};

enum ERefineType
{
	REFINE_TYPE_NORMAL,
	REFINE_TYPE_NOT_USED1,
	REFINE_TYPE_SCROLL,
	REFINE_TYPE_HYUNIRON,
	REFINE_TYPE_MONEY_ONLY,
	REFINE_TYPE_MUSIN,
	REFINE_TYPE_BDRAGON,
	REFINE_TYPE_STONE_OF_BLESS,
};
#ifdef __SASH_SYSTEM__
enum ESashInfo
{
	SASH_GRADE_VALUE_FIELD = 0,
	SASH_ABSORPTION_SOCKET = 0,
	SASH_ABSORBED_SOCKET = 1,
	SASH_GRADE_1_ABS = 1,
	SASH_GRADE_2_ABS = 5,
	SASH_GRADE_3_ABS = 10,
	SASH_GRADE_4_ABS_MIN = 11,
	SASH_GRADE_4_ABS_MAX = 25,
	SASH_GRADE_4_ABS_MAX_COMB = 19,
	SASH_GRADE_4_ABS_RANGE = 5,
	SASH_EFFECT_FROM_ABS = 19,
	SASH_CLEAN_ATTR_VALUE0 = 7,
	SASH_WINDOW_MAX_MATERIALS = 2,
	SASH_GRADE_1_PRICE = 100000,
	SASH_GRADE_2_PRICE = 200000,
	SASH_GRADE_3_PRICE = 300000,
	SASH_GRADE_4_PRICE = 500000,
	SASH_COMBINE_GRADE_1 = 70,
	SASH_COMBINE_GRADE_2 = 60,
	SASH_COMBINE_GRADE_3 = 50,
	SASH_COMBINE_GRADE_4 = 40,
};
#endif
#endif
