#ifndef __INC_METIN_II_LENGTH_H__
#define __INC_METIN_II_LENGTH_H__

#include "CommonDefines.h"

#define WORD_MAX 0xffff

#ifdef ENABLE_ITEMSHOP
enum EItemShopPriceType : uint8_t
{
	ITEMSHOP_PRICE_COIN = 1,
	ITEMSHOP_PRICE_JETON,
	ITEMSHOP_PRICE_MAX,
};
#endif

#ifdef ENABLE_SWITCHBOT

enum SwitchbotValues
{
	SWITCHBOT_SLOT_COUNT = 5,
	SWITCHBOT_ALTERNATIVE_COUNT = 5,
	//1 = Switching Item
	//2 = Yang
	SWITCHBOT_PRICE_TYPE = 1,
	//Amount Swtichting Items the Yang-Price
	SWITCHBOT_PRICE_AMOUNT = 1,
};

const DWORD c_arSwitchingItems[4] =
{
	39028,
	71084,
	76014,
	71151,
};
#endif


enum EMisc
{
	VOICE_CHAT_MIN_LEVEL = 30,
	MAX_HOST_LENGTH			= 15,
	IP_ADDRESS_LENGTH		= 15,
	LOGIN_MAX_LEN			= 30,
	PASSWD_MAX_LEN			= 16,
#ifdef ENABLE_PLAYER_PER_ACCOUNT5
	PLAYER_PER_ACCOUNT		= 5,
#else
	PLAYER_PER_ACCOUNT		= 4,
#endif
	ACCOUNT_STATUS_MAX_LEN	= 8,
	CHARACTER_NAME_MAX_LEN	= 24,
	SHOP_SIGN_MAX_LEN		= 32,
#ifdef ENABLE_SPECIAL_COSTUME_ATTR
	SPECIAL_ATTR_COSTUME_BODY_LIMIT=3,
	SPECIAL_ATTR_COSTUME_HAIR_LIMIT=3,
	SPECIAL_ATTR_COSTUME_WEAPON_LIMIT=3,
#ifdef ENABLE_MOUNT_SKIN
	SPECIAL_ATTR_COSTUME_MOUNT_SKIN_LIMIT=3,
#endif
#ifdef ENABLE_SASH_COSTUME_SYSTEM
	SPECIAL_ATTR_COSTUME_SASH_SKIN_LIMIT=3,
#endif
#ifdef __ITEM_SHINING__
	SPECIAL_ATTR_COSTUME_SHINING_LIMIT=3,
#endif
#endif

#ifdef ENABLE_NEW_PET_SYSTEM
	PET_MAX_LEVEL_CONST = 120,
	PET_MAX_EVOLUTION_CONST = 3,
	PET_MAX_SKILL_LEVEL_CONST = 20,
	PET_HATCH_COST = 100000,
	PET_APPLY_MAX_NUM = 3,
	PET_SKILLS_MAX_NUM = 3,
#endif
#ifdef VOTE_BUFF_RENEWAL
	V4B_AFFECT_DURATION = 24 * 3600, // 24 hours
#endif
	INVENTORY_PAGE_COLUMN	= 5, // 5 (default)
	INVENTORY_PAGE_ROW		= 9, // 9 (default)
	INVENTORY_PAGE_SIZE		= INVENTORY_PAGE_COLUMN*INVENTORY_PAGE_ROW,
#ifdef ENABLE_EXTEND_INVEN_SYSTEM
	INVENTORY_PAGE_COUNT	= 4, // 2 (default)
#else
	INVENTORY_PAGE_COUNT	= 2, // 2 (default)
#endif
	INVENTORY_MAX_NUM		= INVENTORY_PAGE_SIZE*INVENTORY_PAGE_COUNT, // 90 (default)
#ifdef __SPIN_WHEEL__
	SPIN_WHEEL_STONE_COUNT = 100,
#endif
	ABILITY_MAX_NUM			= 50,
	EMPIRE_MAX_NUM			= 4,
	BANWORD_MAX_LEN			= 24,
	SMS_MAX_LEN				= 80,
	MOBILE_MAX_LEN			= 32,
	SOCIAL_ID_MAX_LEN		= 18,

#ifdef ENABLE_BUY_WITH_ITEM
	MAX_SHOP_PRICES = 5,
#endif

	GUILD_NAME_MAX_LEN		= 12,

	SHOP_HOST_ITEM_MAX_NUM	= 40,	/* È£½ºÆ®ÀÇ ÃÖ´ë ¾ÆÀÌÅÛ °³¼ö */
	SHOP_GUEST_ITEM_MAX_NUM = 18,	/* °Ô½ºÆ®ÀÇ ÃÖ´ë ¾ÆÀÌÅÛ °³¼ö */

	SHOP_PRICELIST_MAX_NUM	= 40,	///< °³ÀÎ»óÁ¡ °¡°ÝÁ¤º¸ ¸®½ºÆ®¿¡¼­ À¯ÁöÇÒ °¡°ÝÁ¤º¸ÀÇ ÃÖ´ë °¹¼ö

	CHAT_MAX_LEN			= 512,

	QUICKSLOT_MAX_NUM		= 36,

	JOURNAL_MAX_NUM			= 2,

	QUERY_MAX_LEN			= 8192,

	FILE_MAX_LEN			= 128,

	PLAYER_EXP_TABLE_MAX	= 120,
	PLAYER_MAX_LEVEL_CONST	= 250,

	GUILD_MAX_LEVEL			= 20,
#ifdef ENABLE_YOHARA_SYSTEM
	PLAYER_CONQUEROR_LEVEL = 30,
#endif

	MOB_MAX_LEVEL			= 100,

	ATTRIBUTE_MAX_VALUE		= 20,
	CHARACTER_PATH_MAX_NUM	= 64,
	SKILL_MAX_NUM			= 255,
	SKILLBOOK_DELAY_MIN		= 64800,
	SKILLBOOK_DELAY_MAX		= 108000,
	SKILL_MAX_LEVEL			= 40,

	APPLY_NAME_MAX_LEN		= 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,

#ifdef __NEW_EXCHANGE_WINDOW__
	EXCHANGE_PAGE_COLUMN = 6,
	EXCHANGE_PAGE_ROW = 4,
#else
	EXCHANGE_PAGE_COLUMN = 4,
	EXCHANGE_PAGE_ROW = 3,
#endif

	MOB_SKILL_MAX_NUM		= 5,

    POINT_MAX_NUM = 255,
	DRAGON_SOUL_BOX_SIZE = 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	MAX_AMOUNT_OF_MALL_BONUS	= 20,

	MAX_PASSPOD = 8 ,

#ifdef UNLOCK_INVENTORY_WORLDARD
	UNLOCK_INVENTORY_MAX = 7,
#endif
	//END_LIMIT_GOLD

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 3,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,

	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,
	
#ifdef ENABLE_SUNG_MAHI_TOWER
	SUNG_MAHI_DAMANGE_MULTIPLIER = 5,
	SUNG_MAHI_DEFENCE_MULTIPLIER = 5,
	SUNG_MAHI_HP_MULTIPLIER = 250,
	SUNG_MAHI_MAX_LEVEL = 50,
#endif

#ifdef ENABLE_RANKING
	RANKING_MAX_CATEGORIES = 20,
#endif

#ifdef ENABLE_SPECIAL_STORAGE

	SPECIAL_INVENTORY_PAGE_COLUMN	= 5,
	SPECIAL_INVENTORY_PAGE_ROW		= 9, 

	SPECIAL_INVENTORY_PAGE_SIZE		= SPECIAL_INVENTORY_PAGE_COLUMN*SPECIAL_INVENTORY_PAGE_ROW,

	SPECIAL_INVENTORY_PAGE_COUNT 	= 4,

	SPECIAL_INVENTORY_MAX_NUM = SPECIAL_INVENTORY_PAGE_SIZE*SPECIAL_INVENTORY_PAGE_COUNT,
#endif

	WEAR_MAX_NUM = 65,

#ifdef ENABLE_IKASHOP_RENEWAL
	OFFLINE_SHOP_NAME_MAX_LEN = 15 + CHARACTER_NAME_MAX_LEN +1,
	OFFLINESHOP_DURATION_MAX_MINUTES = 8 * 24 * 60,
	OFFLINESHOP_AUCTION_DURATION = 1 * 24 * 60,
#ifdef USE_OFFLINESHOP_SEARCH_V2
    OFFLINESHOP_SECONDS_PER_SEARCH = 1,
    OFFLINESHOP_MAX_SEARCH_RESULT = 100,
#else
    OFFLINESHOP_SECONDS_PER_SEARCH = 5,
    OFFLINESHOP_MAX_SEARCH_RESULT = 2500,
#endif
	OFFLINESHOP_SECONDS_PER_OFFER = 5,
	OFFLINESHOP_RESTORE_DURATION_COST = 1000000,
	OFFLINESHOP_MIN_OFFER_PERCENTAGE = 30,
	OFFLINESHOP_MAX_WEIGHT_PER_PLAYER = 2500,
	OFFLINESHOP_MAX_PENDING_OFFERS = 30,
	OFFLINESHOP_MAX_SAFEBOX_SIZE = 100,
#ifdef ENABLE_CHEQUE_SYSTEM
	YANG_PER_CHEQUE = 100000000,
#endif
#ifdef EXTEND_IKASHOP_PRO
	OFFLINESHOP_NOTIFICATION_FORMAT_LEN = 40,
#endif
#ifdef EXTEND_IKASHOP_ULTIMATE
	OFFLINESHOP_EXPIRING_SALE_HISTORY = 60*60*24*8, // 8 days
	OFFLINESHOP_SALE_HISTORY_COOLDOWN = 60*60*8, // 8 hours
	OFFSHOP_DECORATION_TIME = 15 * 24 * 60,
#ifdef USE_IKASHOP_UI_RENEWED
	OFFSHOP_LOCK_INDEX_INIT = (10 * 8) * 2,
#else
	OFFSHOP_LOCK_INDEX_INIT = 15*10, // first page unlocked by default
#endif
	OFFSHOP_SEARCH_PREMIUM_TIME = 15*24*60*60,
#endif
#endif

	BATTLE_PASS_MAX_ITEMS 			= 4,
/**
	 **** ÇöÀç±îÁö ÇÒ´ç µÈ ¾ÆÀÌÅÛ ¿µ¿ª Á¤¸® (DB»ó Item Position) ****
	+------------------------------------------------------+ 0
	| Ä³¸¯ÅÍ ±âº» ÀÎº¥Åä¸® (45Ä­ * 2ÆäÀÌÁö) 90Ä­           |
	+------------------------------------------------------+ 90 = INVENTORY_MAX_NUM(90)
	| Ä³¸¯ÅÍ Àåºñ Ã¢ (Âø¿ëÁßÀÎ ¾ÆÀÌÅÛ) 32Ä­                |
	+------------------------------------------------------+ 122 = INVENTORY_MAX_NUM(90) + WEAR_MAX_NUM(32)
	| ¿ëÈ¥¼® Àåºñ Ã¢ (Âø¿ëÁßÀÎ ¿ëÈ¥¼®) 12Ä­                |
	+------------------------------------------------------+ 134 = 122 + DS_SLOT_MAX(6) * DRAGON_SOUL_DECK_MAX_NUM(2)
	| ¿ëÈ¥¼® Àåºñ Ã¢ ¿¹¾à (¾ÆÁ÷ ¹Ì»ç¿ë) 18Ä­               |
	+------------------------------------------------------+ 152 = 134 + DS_SLOT_MAX(6) * DRAGON_SOUL_DECK_RESERVED_MAX_NUM(3)
	| º§Æ® ÀÎº¥Åä¸® (º§Æ® Âø¿ë½Ã¿¡¸¸ º§Æ® ·¹º§¿¡ µû¶ó È°¼º)|
	+------------------------------------------------------+ 168 = 152 + BELT_INVENTORY_SLOT_COUNT(16) = INVENTORY_AND_EQUIP_CELL_MAX
	| ¹Ì»ç¿ë                                               |
	+------------------------------------------------------+ ??
*/
};

#ifdef __GEM_SYSTEM__
enum GemLength
{
	REFRESH_TIME = 60*60*5,
	OPEN_GEM_SLOT_ITEM = 39064,
	OPEN_GEM_REFRESH_ITEM = 39063,
	GEM_MAX = 1000000, // 999999
};
#endif

#ifdef CHANGE_EQUIP_WORLDARD 
enum ChangeEquipConfig
{
	CHANGE_EQUIP_PAGE_EXTRA = 3,
	//CHANGE_EQUIP_SLOT_COUNT = 29*CHANGE_EQUIP_PAGE_EXTRA,
	CHANGE_EQUIP_SLOT_COUNT = 34*CHANGE_EQUIP_PAGE_EXTRA,
};
#endif

#ifdef ENABLE_MULTILANGUAGE_SYSTEM
enum ELocale
{
	LOCALE_YMIR,
	LOCALE_EN, // United Kingdom
	LOCALE_DE, // Germany
	LOCALE_TR, // Turkey
	LOCALE_PT, // Portugal
	LOCALE_ES, // Spain
	LOCALE_FR, // France
	LOCALE_RO, // Romania
	LOCALE_PL, // Poland
	LOCALE_IT, // Italy
	LOCALE_CZ, // Czech
	LOCALE_HU, // Hungary
	LOCALE_MAX_NUM,
	LOCALE_DEFAULT = LOCALE_EN,
};
#endif

enum EMatrixCard
{
	MATRIX_CODE_MAX_LEN		= 192,
	MATRIX_ANSWER_MAX_LEN	= 8,
};

// #ifdef ENABLE_PENDANT_SYSTEM_RENEWAL
// enum EPendantList
// {
	// PENDANT_FIRE,
	// PENDANT_ICE,
	// PENDANT_EARTH, 
	// PENDANT_DARK,
	// PENDANT_WIND,
	// PENDANT_LIGHTNING,

	// PENDANT_MAX_NUM,
// };
// #endif

enum EWearPositions
{
	WEAR_BODY,		// 0
	WEAR_HEAD,		// 1
	WEAR_FOOTS,		// 2
	WEAR_WRIST,		// 3
	WEAR_WEAPON,	// 4
	WEAR_NECK,		// 5
	WEAR_EAR,		// 6
	WEAR_UNIQUE1,	// 7
	WEAR_UNIQUE2,	// 8
	WEAR_ARROW,		// 9
	WEAR_SHIELD,	// 10
    WEAR_ABILITY1,  // 11
    WEAR_ABILITY2,  // 12
    WEAR_ABILITY3,  // 13
    WEAR_ABILITY4,  // 14
    WEAR_ABILITY5,  // 15
    WEAR_ABILITY6,  // 16
    WEAR_ABILITY7,  // 17
    WEAR_ABILITY8,  // 18
	WEAR_COSTUME_BODY,	// 19
	WEAR_COSTUME_HAIR,	// 20
#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	WEAR_COSTUME_MOUNT, //21
#endif
#ifdef __SASH_SYSTEM__
	WEAR_COSTUME_SASH,  //22
#endif
	WEAR_BELT,			// 23
#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	WEAR_COSTUME_WEAPON, // 24
#endif
	WEAR_RINGS_1,		// 25
	WEAR_RINGS_2,		// 26
#ifdef ENABLE_SASH_COSTUME_SYSTEM
	WEAR_COSTUME_NEW_SASH,  //27
#endif
#ifdef ENABLE_YOHARA_SYSTEM
	WEAR_GLOVE, // 28
#endif
#ifdef ITEM_TALISMAN_EQUIPMENT
	WEAR_PENDANT, // 29
#endif
#ifdef ENABLE_NEW_PET_SYSTEM
	WEAR_OLD_PET, // 30
	WEAR_PET, // 31
#endif
#ifdef __ITEM_SHINING__
	WEAR_SHINING_WEAPON_1,//32
	WEAR_SHINING_ARMOR_1, //33
	WEAR_SHINING_SPECIAL, // 34
#endif
#ifdef ENABLE_MOUNT_SKIN
	WEAR_COSTUME_MOUNT_SKIN,//35
#endif
#ifdef __BUFFI_SUPPORT__
	WEAR_BUFFI_BODY,
	WEAR_BUFFI_HEAD,
	WEAR_BUFFI_WEAPON,
	WEAR_BUFFI_SASH,
#ifdef __BUFFI_SHINING__
	WEAR_BUFFI_SHINING_WEAPON,
	WEAR_BUFFI_SHINING_ARMOR,
#endif
	WEAR_BUFFI_RING_0,
	WEAR_BUFFI_RING_1,
	WEAR_BUFFI_RING_2,
#endif
#ifdef ENABLE_NEWEQ
	WEAR_RING_SLOT1,
	WEAR_RING_SLOT2,
	WEAR_RING_SLOT3,
	WEAR_RING_SLOT4,
	WEAR_RING_SLOT5,
	WEAR_RING_SLOT6,
	WEAR_RING_SLOT7,
#endif
#ifdef __AURA_SYSTEM__
	WEAR_COSTUME_AURA,
#endif

	WEAR_PENDANT_FIRE,
	WEAR_PENDANT_ICE,
	WEAR_PENDANT_THUNDER,
	WEAR_PENDANT_WIND,
	WEAR_PENDANT_DARK,
	WEAR_PENDANT_EARTH,

	WEAR_SPECIAL_RING1,
	WEAR_SPECIAL_RING2,
	WEAR_BOOST_ARMOR,
	WEAR_BOOST_HEAD,
	WEAR_BOOST_WEAPON,
	WEAR_PENDANT_SOUL_FIRST,
	WEAR_PENDANT_SOUL_SECOND,

	// WEAR_MAX_NUM,	// 36
};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,	// NOTE: Áß¿ä! ¾ÆÁ÷ »ç¿ëÁßÀÌÁø ¾ÊÁö¸¸, 3ÆäÀÌÁö ºÐ·®À» ¿¹¾à ÇØ µÒ. DS DECKÀ» ´Ã¸± °æ¿ì ¹Ýµå½Ã ±× ¼ö¸¸Å­ RESERVED¿¡¼­ Â÷°¨ÇØ¾ß ÇÔ!
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10  /* ±â¼ú ÃÖ´ë ·¹º§ */

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,	/* ½ÅÃ¼Àû ¾îºô¸®Æ¼ */
	CATEGORY_MENTAL,	/* Á¤½ÅÀû ¾îºô¸®Æ¼ */
	CATEGORY_ATTRIBUTE,	/* ´É·Â ¾îºô¸®Æ¼ */
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
#ifdef ENABLE_WOLFMAN_CHARACTER
	JOB_WOLFMAN,		// ¼öÀÎÁ·. °³¹ßÄÚµå¸íÀÌ WOLFMAN. (±âÈ¹ÀÚ°¡ Á¤Çß¾¸. ³ªÁß¿¡ WOLF GIRL »ý°Üµµ ³ªÇÑÅ× ¸Ó¶óÇÏÁö¸¶¼À¤Ð¤Ð)
#endif
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL = (1 << 0),
	RACE_FLAG_UNDEAD = (1 << 1),
	RACE_FLAG_DEVIL = (1 << 2),
	RACE_FLAG_HUMAN = (1 << 3),
	RACE_FLAG_ORC = (1 << 4),
	RACE_FLAG_MILGYO = (1 << 5),
	RACE_FLAG_INSECT = (1 << 6),
	RACE_FLAG_FIRE = (1 << 7),
	RACE_FLAG_ICE = (1 << 8),
	RACE_FLAG_DESERT = (1 << 9),
	RACE_FLAG_TREE = (1 << 10),
	//RACE_FLAG_ELEC = (1 << 11),
	//RACE_FLAG_WIND = (1 << 12),
	//RACE_FLAG_EARTH = (1 << 13),
	//RACE_FLAG_DARK = (1 << 14),
	RACE_FLAG_ATT_ELEC = (1 << 11),
	RACE_FLAG_ATT_FIRE = (1 << 12),
	RACE_FLAG_ATT_ICE = (1 << 13),
	RACE_FLAG_ATT_WIND = (1 << 14),
	RACE_FLAG_ATT_EARTH = (1 << 15),
	RACE_FLAG_ATT_DARK = (1 << 16),
	RACE_FLAG_ZODIAC	= (1 << 17),
};


enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
#ifdef __SASH_SYSTEM__
	PART_SASH,
#endif
	PART_ARROW_TYPE,
	PART_WEAPON_SUB,
#ifdef __AURA_SYSTEM__
	PART_AURA,
#endif
	PART_MAX_NUM,

};

enum EChatType
{
	CHAT_TYPE_TALKING,	/* ±×³É Ã¤ÆÃ */
	CHAT_TYPE_INFO,	/* Á¤º¸ (¾ÆÀÌÅÛÀ» Áý¾ú´Ù, °æÇèÄ¡¸¦ ¾ò¾ú´Ù. µî) */
	CHAT_TYPE_NOTICE,	/* °øÁö»çÇ× */
	CHAT_TYPE_PARTY,	/* ÆÄÆ¼¸» */
	CHAT_TYPE_GUILD,	/* ±æµå¸» */
	CHAT_TYPE_COMMAND,	/* ÀÏ¹Ý ¸í·É */
	CHAT_TYPE_SHOUT,	/* ¿ÜÄ¡±â */
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
	// CHAT_TYPE_UNK_10,
#ifdef ENABLE_DICE_SYSTEM
	CHAT_TYPE_DICE_INFO, //11
#endif
#ifdef __CHAT_SETTINGS__
	CHAT_TYPE_EXP_INFO,
	CHAT_TYPE_ITEM_INFO,
	CHAT_TYPE_MONEY_INFO,
#endif
#ifdef dracaryS_DUNGEON_LIB
	CHAT_TYPE_MISSION,
#endif
	CHAT_TYPE_MAX_NUM,
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL		= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR		= 4,
	WHISPER_TYPE_GM			= 5,
	WHISPER_TYPE_SYSTEM		= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR,
	GM_DISABLE,
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO,
#ifdef ENABLE_NEW_PET_SYSTEM
	CHAR_TYPE_PET,
#endif
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,			// 0
	APPLY_MAX_HP,		// 1
	APPLY_MAX_SP,		// 2
	APPLY_CON,			// 3
	APPLY_INT,			// 4
	APPLY_STR,			// 5
	APPLY_DEX,			// 6
	APPLY_ATT_SPEED,	// 7
	APPLY_MOV_SPEED,	// 8
	APPLY_CAST_SPEED,	// 9
	APPLY_HP_REGEN,		// 10
	APPLY_SP_REGEN,		// 11
	APPLY_POISON_PCT,	// 12
	APPLY_STUN_PCT,		// 13
	APPLY_SLOW_PCT,		// 14
	APPLY_CRITICAL_PCT,		// 15
	APPLY_PENETRATE_PCT,	// 16
	APPLY_ATTBONUS_HUMAN,	// 17
	APPLY_ATTBONUS_ANIMAL,	// 18
	APPLY_ATTBONUS_ORC,		// 19
	APPLY_ATTBONUS_MILGYO,	// 20
	APPLY_ATTBONUS_UNDEAD,	// 21
	APPLY_ATTBONUS_DEVIL,	// 22
	APPLY_STEAL_HP,			// 23
	APPLY_STEAL_SP,			// 24
	APPLY_MANA_BURN_PCT,	// 25
	APPLY_DAMAGE_SP_RECOVER,	// 26
	APPLY_BLOCK,			// 27
	APPLY_DODGE,			// 28
	APPLY_RESIST_SWORD,		// 29
	APPLY_RESIST_TWOHAND,	// 30
	APPLY_RESIST_DAGGER,	// 31
	APPLY_RESIST_BELL,		// 32
	APPLY_RESIST_FAN,		// 33
	APPLY_RESIST_BOW,		// 34
	APPLY_RESIST_FIRE,		// 35
	APPLY_RESIST_ELEC,		// 36
	APPLY_RESIST_MAGIC,		// 37
	APPLY_RESIST_WIND,		// 38
	APPLY_REFLECT_MELEE,	// 39
	APPLY_REFLECT_CURSE,	// 40
	APPLY_POISON_REDUCE,	// 41
	APPLY_KILL_SP_RECOVER,	// 42
	APPLY_EXP_DOUBLE_BONUS,	// 43
	APPLY_GOLD_DOUBLE_BONUS,	// 44
	APPLY_ITEM_DROP_BONUS,	// 45
	APPLY_POTION_BONUS,		// 46
	APPLY_KILL_HP_RECOVER,	// 47
	APPLY_IMMUNE_STUN,		// 48
	APPLY_IMMUNE_SLOW,		// 49
	APPLY_IMMUNE_FALL,		// 50
	APPLY_SKILL,			// 51
	APPLY_BOW_DISTANCE,		// 52
	APPLY_ATT_GRADE_BONUS,	// 53
	APPLY_DEF_GRADE_BONUS,	// 54
	APPLY_MAGIC_ATT_GRADE,	// 55
	APPLY_MAGIC_DEF_GRADE,	// 56
	APPLY_CURSE_PCT,		// 57
	APPLY_MAX_STAMINA,		// 58
	APPLY_ATTBONUS_WARRIOR,	// 59
	APPLY_ATTBONUS_ASSASSIN,	// 60
	APPLY_ATTBONUS_SURA,	// 61
	APPLY_ATTBONUS_SHAMAN,	// 62
	APPLY_ATTBONUS_MONSTER,	// 63
	APPLY_MALL_ATTBONUS,			// 64 °ø°Ý·Â +x%
	APPLY_MALL_DEFBONUS,			// 65 ¹æ¾î·Â +x%
	APPLY_MALL_EXPBONUS,			// 66 °æÇèÄ¡ +x%
	APPLY_MALL_ITEMBONUS,			// 67 ¾ÆÀÌÅÛ µå·ÓÀ² x/10¹è
	APPLY_MALL_GOLDBONUS,			// 68 µ· µå·ÓÀ² x/10¹è
	APPLY_MAX_HP_PCT,				// 69 ÃÖ´ë »ý¸í·Â +x%
	APPLY_MAX_SP_PCT,				// 70 ÃÖ´ë Á¤½Å·Â +x%
	APPLY_SKILL_DAMAGE_BONUS,		// 71 ½ºÅ³ µ¥¹ÌÁö * (100+x)%
	APPLY_NORMAL_HIT_DAMAGE_BONUS,	// 72 ÆòÅ¸ µ¥¹ÌÁö * (100+x)%
	APPLY_SKILL_DEFEND_BONUS,		// 73 ½ºÅ³ µ¥¹ÌÁö ¹æ¾î * (100-x)%
	APPLY_NORMAL_HIT_DEFEND_BONUS,	// 74 ÆòÅ¸ µ¥¹ÌÁö ¹æ¾î * (100-x)%
	APPLY_PC_BANG_EXP_BONUS,		// 75 PC¹æ ¾ÆÀÌÅÛ EXP º¸³Ê½º
	APPLY_PC_BANG_DROP_BONUS,		// 76 PC¹æ ¾ÆÀÌÅÛ µå·ÓÀ² º¸³Ê½º

	APPLY_EXTRACT_HP_PCT,			// 77 »ç¿ë½Ã HP ¼Ò¸ð

	APPLY_RESIST_WARRIOR,			// 78 ¹«»ç¿¡°Ô ÀúÇ×
	APPLY_RESIST_ASSASSIN,			// 79 ÀÚ°´¿¡°Ô ÀúÇ×
	APPLY_RESIST_SURA,				// 80 ¼ö¶ó¿¡°Ô ÀúÇ×
	APPLY_RESIST_SHAMAN,			// 81 ¹«´ç¿¡°Ô ÀúÇ×
	APPLY_ENERGY,					// 82 ±â·Â
	APPLY_DEF_GRADE,				// 83 ¹æ¾î·Â. DEF_GRADE_BONUS´Â Å¬¶ó¿¡¼­ µÎ¹è·Î º¸¿©Áö´Â ÀÇµµµÈ ¹ö±×(...)°¡ ÀÖ´Ù.
	APPLY_COSTUME_ATTR_BONUS,		// 84 ÄÚ½ºÆ¬ ¾ÆÀÌÅÛ¿¡ ºÙÀº ¼Ó¼ºÄ¡ º¸³Ê½º
	APPLY_MAGIC_ATTBONUS_PER,		// 85 ¸¶¹ý °ø°Ý·Â +x%
	APPLY_MELEE_MAGIC_ATTBONUS_PER,			// 86 ¸¶¹ý + ¹Ð¸® °ø°Ý·Â +x%

	APPLY_RESIST_ICE,		// 87 ³Ã±â ÀúÇ×
	APPLY_RESIST_EARTH,		// 88 ´ëÁö ÀúÇ×
	APPLY_RESIST_DARK,		// 89 ¾îµÒ ÀúÇ×

	APPLY_ANTI_CRITICAL_PCT,	//90 Å©¸®Æ¼ÄÃ ÀúÇ×
	APPLY_ANTI_PENETRATE_PCT,	//91 °üÅëÅ¸°Ý ÀúÇ×

// #ifdef ENABLE_WOLFMAN_CHARACTER
	APPLY_BLEEDING_REDUCE			= 92,		//92
	APPLY_BLEEDING_PCT				= 93,		//93
	APPLY_ATTBONUS_WOLFMAN			= 94,		//94 ¼öÀÎÁ·¿¡°Ô °­ÇÔ
	APPLY_RESIST_WOLFMAN			= 95,		//95 ¼öÀÎÁ·¿¡°Ô ÀúÇ×
	APPLY_RESIST_CLAW				= 96,		//96 CLAW¹«±â¿¡ ÀúÇ×
// #endif

// #ifdef ENABLE_ACCE_COSTUME_SYSTEM
	APPLY_ACCEDRAIN_RATE			= 97,			//97
// #endif

// #ifdef ENABLE_MAGIC_REDUCTION_SYSTEM
	APPLY_RESIST_MAGIC_REDUCTION	= 98,	//98
// #endif

// #ifdef ENABLE_NEW_BONUS_WORLDARD
	APPLY_RESIST_HUMAN				= 99,
// #endif
// #ifdef ELEMENT_NEW_BONUSES
	APPLY_ATTBONUS_ELEC  = 100,
	APPLY_ATTBONUS_FIRE  = 101,
	APPLY_ATTBONUS_ICE	 = 102,
	APPLY_ATTBONUS_WIND  = 103,
	APPLY_ATTBONUS_EARTH = 104,
	APPLY_ATTBONUS_DARK = 105,
// #endif
// #ifdef ENABLE_YOHARA_SYSTEM
	APPLY_RANDOM = 118,
	APPLY_SUNGMA_STR = 119,
	APPLY_SUNGMA_HP = 120,
	APPLY_SUNGMA_MOVE = 121,
	APPLY_SUNGMA_IMMUNE = 122,
// #endif
// #ifdef ELEMENT_NEW_BONUSES
	APPLY_ENCHANT_ELEC = 123,
	APPLY_ENCHANT_FIRE = 124,
	APPLY_ENCHANT_ICE = 125,
	APPLY_ENCHANT_WIND  = 126,
	APPLY_ENCHANT_EARTH = 127,
	APPLY_ENCHANT_DARK = 128,
	APPLY_ATTBONUS_SWORD = 129,		
	APPLY_ATTBONUS_TWOHAND = 130,	
	APPLY_ATTBONUS_DAGGER = 131,	
	APPLY_ATTBONUS_BELL = 132,		
	APPLY_ATTBONUS_FAN = 133,		
	APPLY_ATTBONUS_BOW = 134,

	APPLY_ATTBONUS_ZODIAC = 135,
	APPLY_ATTBONUS_DESERT = 136,
	APPLY_ATTBONUS_INSECT = 137,	
// #ifdef ENABLE_WOLFMAN_CHARACTER
	APPLY_ATTBONUS_CLAW = 138,
// #endif
// #endif
// #ifdef NEW_BONUS
	APPLY_ATTBONUS_STONE= 139,
	APPLY_ATTBONUS_BOSS= 140,
// #endif
// #ifdef ENABLE_YOHARA_SYSTEM
	APPLY_HIT_PCT = 141,
	APPLY_RESIST_MOUNT_FALL = 142,
	APPLY_MONSTER_DEFEND_BONUS = 143,
// #endif
// #ifdef USE_DROP_AFFECT_BONUSES
	APPLY_DOUBLE_DROP_METIN = 144,
	APPLY_DOUBLE_DROP_BOSS = 145,
// #endif
	MAX_APPLY_NUM = 150,
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
//#ifdef ENABLE_SPECIAL_STORAGE
	UPGRADE_INVENTORY,
	BOOK_INVENTORY,
	STONE_INVENTORY,
	CHANGE_INVENTORY,
	COSTUME_INVENTORY,
	CHEST_INVENTORY,
//#endif
//#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
//#endif
//#ifdef CHANGE_EQUIP_WORLDARD
	CHANGE_EQUIP,
//#endif
	BELT_INVENTORY,
	GROUND,
//#ifdef ENABLE_IKASHOP_RENEWAL
	IKASHOP_OFFLINESHOP,
	IKASHOP_SAFEBOX,
	IKASHOP_AUCTION,
//#endif
//#ifdef __AURA_SYSTEM__
	AURA_REFINE,
//#endif
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE	= (1 << 0),
	AIFLAG_NOMOVE	= (1 << 1),
	AIFLAG_COWARD	= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB = (1 << 6 ),
	AIFLAG_BERSERK	= (1 << 7),
	AIFLAG_STONESKIN	= (1 << 8),
	AIFLAG_GODSPEED	= (1 << 9),
	AIFLAG_DEATHBLOW	= (1 << 10),
	AIFLAG_REVIVE		= (1 << 11),
#ifdef ENABLE_SUNG_MAHI_TOWER
	AIFLAG_NOATTACK		= (1 << 12),
#endif
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_BLEEDING_AS_POISON)
	MOB_ENCHANT_BLEEDING,
#endif
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_CLAW_AS_DAGGER)
	MOB_RESIST_CLAW,
#endif
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_BLEEDING_AS_POISON)
	MOB_RESIST_BLEEDING,
#endif
	MOB_RESISTS_MAX_NUM
};

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
		/*
		   SKILL_ATTR_TYPE_FIRE,
		   SKILL_ATTR_TYPE_ICE,
		   SKILL_ATTR_TYPE_ELEC,
		   SKILL_ATTR_TYPE_DARK,
		   */
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60, // 1½Ã°£
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

enum EAttributeSet
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY,
	ATTRIBUTE_SET_WRIST,
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
#ifdef ADD_NEW_BONUS_INTO_COSTUME
	ATTRIBUTE_SET_COSTUME_BODY,
	ATTRIBUTE_SET_COSTUME_HEAD,
	ATTRIBUTE_SET_COSTUME_WEAPON,
#endif
	ATTRIBUTE_SET_NEW_RINGS,
#ifdef ENABLE_YOHARA_SYSTEM
	ATTRIBUTE_SET_GLOVE,
#endif
#ifdef ITEM_TALISMAN_EQUIPMENT
	ATTRIBUTE_SET_PENDANT,
#endif
	ATTRIBUTE_SET_BOOSTER,
	ATTRIBUTE_SET_PENDANT_SOUL,

	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,		// °æÇèÄ¡°¡ 1.2¹è
	PREMIUM_ITEM,		// ¾ÆÀÌÅÛ µå·ÓÀ²ÀÌ 2¹è
	PREMIUM_SAFEBOX,		// Ã¢°í°¡ 1Ä­¿¡¼­ 3Ä­
	PREMIUM_AUTOLOOT,		// µ· ÀÚµ¿ ÁÝ±â
	PREMIUM_FISH_MIND,		// °í±Þ ¹°°í±â ³¬ÀÏ È®·ü »ó½Â
	PREMIUM_MARRIAGE_FAST,	// ±Ý½Ç Áõ°¡ ¾çÀ» ºü¸£°ÔÇÕ´Ï´Ù.
	PREMIUM_GOLD,		// µ· µå·ÓÀ²ÀÌ 1.5¹è
#if defined(__AUTOMATIC_HUNTING_SYSTEM__)
	//PREMIUM_AUTO_USE,
#endif
	PREMIUM_MAX_NUM = 9
};

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,		// ¶ó¸¶´Ü ÃÊ½Â´ÞÀÇ ¹ÝÁö(71135) Âø¿ëÇÒ ¶§ ÀÌÆåÆ® (¹ßµ¿ÀÌÆåÆ®ÀÓ, Áö¼ÓÀÌÆåÆ® ¾Æ´Ô)
	SE_EQUIP_HALLOWEEN_CANDY,		// ÇÒ·ÎÀ© »çÅÁÀ» Âø¿ë(-_-;)ÇÑ ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
	SE_EQUIP_HAPPINESS_RING,		// Å©¸®½º¸¶½º Çàº¹ÀÇ ¹ÝÁö(71143) Âø¿ëÇÒ ¶§ ÀÌÆåÆ® (¹ßµ¿ÀÌÆåÆ®ÀÓ, Áö¼ÓÀÌÆåÆ® ¾Æ´Ô)
	SE_EQUIP_LOVE_PENDANT,		// ¹ß·»Å¸ÀÎ »ç¶ûÀÇ ÆÒ´øÆ®(71145) Âø¿ëÇÒ ¶§ ÀÌÆåÆ® (¹ßµ¿ÀÌÆåÆ®ÀÓ, Áö¼ÓÀÌÆåÆ® ¾Æ´Ô)
#if defined(WJ_COMBAT_ZONE)
	SE_COMBAT_ZONE_POTION,
#endif
#ifdef __SASH_SYSTEM__
	SE_EFFECT_SASH_SUCCEDED,
	SE_EFFECT_SASH_EQUIP,
#endif
#ifdef __VERSION_162__
	SE_EFFECT_HEALER,
#endif
#ifdef ENABLE_ZODIAC_MISSION
	EFFECT_SKILL_DAMAGE_ZONE,
	EFFECT_SKILL_DAMAGE_ZONE_BUYUK,
	EFFECT_SKILL_DAMAGE_ZONE_ORTA,
	EFFECT_SKILL_DAMAGE_ZONE_KUCUK,
	EFFECT_SKILL_SAFE_ZONE,
	EFFECT_SKILL_SAFE_ZONE_BUYUK,
	EFFECT_SKILL_SAFE_ZONE_ORTA,
	EFFECT_SKILL_SAFE_ZONE_KUCUK,
	EFFECT_METEOR,
	EFFECT_BEAD_RAIN,
	EFFECT_FALL_ROCK,
	EFFECT_ARROW_RAIN,
	EFFECT_HORSE_DROP,
	EFFECT_EGG_DROP,
	EFFECT_DEAPO_BOOM,
#endif
#ifdef ENABLE_QUEEN_NETHIS
	SE_EFFECT_SNAKE_REGEN,
#endif
#ifdef ENABLE_VOICE_CHAT
	SE_VOICE_CHAT,
#endif
};

enum ETeenFlags
{
	TEENFLAG_NONE = 0,
	TEENFLAG_1HOUR,
	TEENFLAG_2HOUR,
	TEENFLAG_3HOUR,
	TEENFLAG_4HOUR,
	TEENFLAG_5HOUR,
};

#include "item_length.h"

// inventoryÀÇ positionÀ» ³ªÅ¸³»´Â ±¸Á¶Ã¼
// int¿ÍÀÇ ¾Ï½ÃÀû Çüº¯È¯ÀÌ ÀÖ´Â ÀÌÀ¯´Â,
// ÀÎº¥ °ü·ÃµÈ ¸ðµç ÇÔ¼ö°¡ window_typeÀº ¹ÞÁö ¾Ê°í, cell ÇÏ³ª¸¸ ¹Þ¾Ò±â ¶§¹®¿¡,(±âÁ¸¿¡´Â ÀÎº¥ÀÌ ÇÏ³ª »ÓÀÌ¾î¼­ inventory typeÀÌ¶õ°Ô ÇÊ¿ä¾ø¾ú±â ¶§¹®¿¡,)
// ÀÎº¥ °ü·Ã ¸ðµç ÇÔ¼ö È£ÃâºÎºÐÀ» ¼öÁ¤ÇÏ´Â °ÍÀÌ ³­°¨ÇÏ±â ¹®ÀÌ´Ù.

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

enum EMisc2
{
	DRAGON_SOUL_EQUIP_SLOT_START = INVENTORY_MAX_NUM + WEAR_MAX_NUM,
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_END + (DS_SLOT_MAX * DRAGON_SOUL_DECK_RESERVED_MAX_NUM),

	BELT_INVENTORY_SLOT_START = DRAGON_SOUL_EQUIP_RESERVED_SLOT_END,
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT,

	INVENTORY_AND_EQUIP_SLOT_MAX = BELT_INVENTORY_SLOT_END,
};

#ifdef ENABLE_SWITCHBOT_WORLDARD
enum SwitchBotMaxNum
{
	SWITCHBOT_SLOT_MAX = 1,
};
#endif

#pragma pack(push, 1)

typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
    SItemPos ()
    {
        window_type = INVENTORY;
		cell = WORD_MAX;
    }

	SItemPos (BYTE _window_type, WORD _cell)
    {
        window_type = _window_type;
        cell = _cell;
    }

	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
		case RESERVED_WINDOW:
			return false;
		case INVENTORY:
		case EQUIPMENT:
		case BELT_INVENTORY:
			return cell < INVENTORY_AND_EQUIP_SLOT_MAX;
		case DRAGON_SOUL_INVENTORY:
			return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);
#ifdef ENABLE_SPECIAL_STORAGE
		case UPGRADE_INVENTORY:
		case BOOK_INVENTORY:
		case STONE_INVENTORY:
		case CHANGE_INVENTORY:
		case COSTUME_INVENTORY:
		case CHEST_INVENTORY:
			return cell < (SPECIAL_INVENTORY_MAX_NUM);
#endif

#ifdef ENABLE_SWITCHBOT
		case SWITCHBOT:
			return cell < SWITCHBOT_SLOT_COUNT;
#endif

#ifdef ENABLE_SWITCHBOT_WORLDARD
		case SWITCHBOT:
			return cell < SWITCHBOT_SLOT_MAX;
#endif
#ifdef CHANGE_EQUIP_WORLDARD
		case CHANGE_EQUIP:
			return cell < CHANGE_EQUIP_SLOT_COUNT;
#endif
		// µ¿ÀûÀ¸·Î Å©±â°¡ Á¤ÇØÁö´Â window´Â valid Ã¼Å©¸¦ ÇÒ ¼ö°¡ ¾ø´Ù.
		case SAFEBOX:
		case MALL:
			return false;
		default:
			return false;
		}
		return false;
	}

	bool IsEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= INVENTORY_MAX_NUM && cell < INVENTORY_MAX_NUM + WEAR_MAX_NUM)
			|| IsDragonSoulEquipPosition();
	}

	bool IsDragonSoulEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= DRAGON_SOUL_EQUIP_SLOT_START && cell < DRAGON_SOUL_EQUIP_SLOT_END);
		//return (DRAGON_SOUL_EQUIP_SLOT_START <= cell) && (DRAGON_SOUL_EQUIP_SLOT_END > cell);
	}

	bool IsBeltInventoryPosition() const
	{
		return (BELT_INVENTORY_SLOT_START <= cell) && (BELT_INVENTORY_SLOT_END > cell);
	}

	bool IsDefaultInventoryPosition() const
	{
		return INVENTORY == window_type && cell < INVENTORY_MAX_NUM;
	}

#ifdef ENABLE_SWITCHBOT
	bool IsSwitchbotPosition() const
	{
		return SWITCHBOT == window_type && cell < SWITCHBOT_SLOT_COUNT;
	}
#endif

#ifdef ENABLE_SWITCHBOT_WORLDARD
	bool IsSwitchBotPosition() const
	{
		return SWITCHBOT == window_type && cell < SWITCHBOT_SLOT_MAX;
	}
#endif

#ifdef CHANGE_EQUIP_WORLDARD
	bool IsChangeEquipPosition() const
	{
		return CHANGE_EQUIP == window_type && cell < CHANGE_EQUIP_SLOT_COUNT;
	}
#endif

	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}
	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
	bool operator!=(const struct SItemPos& rhs) const
	{
		return (window_type != rhs.window_type) || (cell != rhs.cell);
	}
} TItemPos;

const TItemPos NPOS (RESERVED_WINDOW, WORD_MAX);

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
#if defined(WJ_COMBAT_ZONE)
	SHOP_COIN_TYPE_COMBAT_ZONE,
#endif
} EShopCoinType;


enum BattlePassTypes
{
	MISSION_TYPE_NONE,

	KILL_MONSTER_BP,
	KILL_MONSTER_SPECIFIC_BP,
	KILL_METIN_BP,
	KILL_BOSS_BP,
	CATCH_FISH_BP,
	FRY_FISH_BP,
	COMBAT_ZONE_POINTS_BP,
	COMBAT_ZONE_KILL_BP,
	DAMAGE_MOBS_BP,
	DAMAGE_METIN_BP,
	DAMAGE_BOSS_BP,
	KILL_PLAYER_BP,
	KILL_PLAYER_OTHER_EMPIRE_BP,
	CRAFT_ITEM_BP,
	ADD_COSTUME_ATTR_BP,
	CHANGE_COSTUME_ATTR_BP,
	CHANGE_ATTR_BP,
	DUNGEON_COMPLETE_SPECIFIC_BP,
	OPEN_CHEST_BP,
	CRAFT_ITEM_SPECIFIC_BP,
	TOKEN_ITEMSHOP_BP,

	MISSION_TYPE_MAX,
};


#ifdef ENABLE_NEW_DETAILS_GUI
enum
{
	KILL_SHINSO,
	KILL_JINNO,
	KILL_CHUNJO,
	KILL_ALLPLAYER,
	KILL_DUELWON,
	KILL_DUELLOST,
	KILL_MONSTER,
	KILL_METINSTONE,
	KILL_BOSSES,
	KILL_MAX_NUM,
};
#endif

#ifdef ENABLE_MINI_GAME_CATCH_KING
enum EMonsterCatchKingEvent
{
	CATCH_KING_NPC = 20506,
	CATCH_KING_DROP_ITEM = 79603,

	CATCH_KING_REWARD_S = 50930,
	CATCH_KING_REWARD_M = 50929,
	CATCH_KING_REWARD_L = 50928,

	CATCH_KING_PLAY_YANG = 30000,
	CATCH_KING_PLAY_ITEM = 79604,
};
#endif	// ENABLE_MINI_GAME_CATCH_KING

#ifdef ENABLE_WHITE_DRAGON
enum
{
	MAP_WHITEDRAGONCAVE_01 = 393,
	MAP_WHITEDRAGONCAVE_02 = 394,
	MAP_WHITEDRAGONCAVE_BOSS = 395,
};
#endif

#ifdef ENABLE_QUEEN_NETHIS
enum {
	MAP_SNAKEVALLEY = 385,
	MAP_SNAKE_TEMPLE_01 = 390,
	MAP_SNAKE_TEMPLE_02 = 391,
};
#endif

#if defined(__AUTOMATIC_HUNTING_SYSTEM__)
enum EAutoUseType
{
	AUTO_ONOFF_START,
	AUTO_ONOFF_ATTACK,
	AUTO_ONOFF_RANGE,
	AUTO_ONOFF_POTION,
	AUTO_ONOFF_SKILL,
	AUTO_ONOFF_RESTART,
	AUTO_ONOFF_ATTACK_STONE,
	AUTO_ONOFF_MAX,
};
#endif

#ifdef __AURA_SYSTEM__
typedef struct SAuraRefineInfo
{
	BYTE bAuraRefineInfoLevel;
	BYTE bAuraRefineInfoExpPercent;
} TAuraRefineInfo;

enum EAuraMisc
{
	AURA_MAX_LEVEL = 250,
	AURA_REFINE_MAX_DISTANCE = 1000,
};

enum EAuraWindowType
{
	AURA_WINDOW_TYPE_ABSORB,
	AURA_WINDOW_TYPE_GROWTH,
	AURA_WINDOW_TYPE_EVOLVE,
	AURA_WINDOW_TYPE_MAX,
};

enum EAuraSlotType
{
	AURA_SLOT_MAIN,
	AURA_SLOT_SUB,
	AURA_SLOT_RESULT,
	AURA_SLOT_MAX
};

enum EAuraGradeType
{
	AURA_GRADE_NONE,
	AURA_GRADE_ORDINARY,
	AURA_GRADE_SIMPLE,
	AURA_GRADE_NOBLE,
	AURA_GRADE_SPARKLING,
	AURA_GRADE_MAGNIFICENT,
	AURA_GRADE_RADIANT,
	AURA_GRADE_MAX_NUM,
};
enum EAuraRefineInfoType
{
	AURA_REFINE_INFO_STEP,
	AURA_REFINE_INFO_LEVEL_MIN,
	AURA_REFINE_INFO_LEVEL_MAX,
	AURA_REFINE_INFO_NEED_EXP,
	AURA_REFINE_INFO_MATERIAL_VNUM,
	AURA_REFINE_INFO_MATERIAL_COUNT,
	AURA_REFINE_INFO_NEED_GOLD,
	AURA_REFINE_INFO_EVOLVE_PCT,
	AURA_REFINE_INFO_MAX
};

enum ERefineInfoType
{
	AURA_REFINE_INFO_SLOT_CURRENT,
	AURA_REFINE_INFO_SLOT_NEXT,
	AURA_REFINE_INFO_SLOT_EVOLVED,
	AURA_REFINE_INFO_SLOT_MAX
};
#endif

#ifdef ENABLE_BATTLEPASS
#include <ctime>

enum EBattlePassMissions : uint8_t
{
    MISSION_NONE,
    MISSION_REACH_LEVEL,
    MISSION_COLLECT_GOLD,
    MISSION_COLLECT_EXP,
    MISSION_KILL_PLAYER,
    MISSION_KILL_MOB,
    MISSION_CATCH_FISH,
    MISSION_MINE,
    MISSION_SEND_SHOUT_MESSAGE,
    MISSION_UPGRADE_OBJECT,
    MISSION_USE_ITEM,
    MISSION_BATTLEPASS_MAX,
};

struct BattlePassInfo
{
    uint8_t id;
    long long start_date;
    long long end_date;
    long long GetRemainingTime() const { return static_cast<long long>(std::difftime(end_date, start_date)); }
};

struct BattlePassMission
{
    int32_t mission_type;
    uint32_t target_object;
    uint64_t target_count;
    uint32_t exp_reward;
    uint16_t min_level;
    uint16_t max_level;

    BattlePassMission(int32_t type, uint32_t object, uint64_t count, uint32_t reward, uint16_t level_min,
                      uint16_t level_max)

        : mission_type(type)
        , target_object(object)
        , target_count(count)
        , exp_reward(reward)
        , min_level(level_min)
        , max_level(level_max)
    {
    }
};
struct TierInfo
{
    uint32_t needed_exp;
    uint32_t reward_vnum;
    uint32_t reward_count;
    uint32_t reward_vnum_premium;
    uint32_t reward_premium_count;

    TierInfo(uint32_t exp, uint32_t vnum, uint32_t count, uint32_t vnum_premium, uint32_t premium_count)
        : needed_exp(exp)
        , reward_vnum(vnum)
        , reward_count(count)
        , reward_vnum_premium(vnum_premium)
        , reward_premium_count(premium_count)
    {
    }
};
struct BattlePassMyMissionInfo
{
    bool completed;
    int32_t total_count;
    bool collected;
};

struct BattlePassMyTierInfo
{
    bool reward_collected;
    bool reward_premium_collected;
};

inline bool BP_IsReachMission(EBattlePassMissions mission) {
    switch (mission)
    {
        case MISSION_REACH_LEVEL:
            return true;
        default:
            return false;
    }
}

#endif

#pragma pack(pop)

#endif
