# coding: utf-8

import localeInfo

BOARD_WIDTH = 242
BOARD_HEIGHT = 396

IMG_PATH = "ikashop/renewed_ui/price_dlg/"

window = {
	"name" : "PriceInput_Dialog",
	"x" : 0,
	"y" : 0,
	"style" : ("movable", "float",),
	"width" : BOARD_WIDTH,
	"height" : BOARD_HEIGHT,
	"children" :
	(
		{
			"name" : "ui_board",
			"type" : "expanded_image",
			"style" : ("attach",),
			"x" : 0,
			"y" : 0,
			"image" : IMG_PATH + "bg.png",
			"children" :
			(
				{
					"name" : "item_name_ui",
					"type" : "text",
					"x" : 0,
					"y" : 24,
					"text" : "",
					"fontname" : "Tahoma:14b",
					"horizontal_align" : "center",
					"text_horizontal_align" : "center",
				},
				{
					"name" : "item_icon_bg_ui",
					"type" : "expanded_image",
					"x" : 0,
					"y" : 24 + 20,
					"image" : IMG_PATH + "item_bg.png",
					"horizontal_align" : "center",
					"children" :
					(
						{
							"name" : "item_icon_ui",
							"type" : "expanded_image",
							"x" : 0,
							"y" : 0,
							"width" : 32,
							"height": 96,
							"image" : "icon/item/money.tga",
							"horizontal_align" : "center",
							"vertical_align" : "center",
						},
					),
				},
				{
					"name" : "average_price_title_ui",
					"type" : "text",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5,
					"text" : localeInfo.PRICEINPUT_DLG_AVERAGE_PRICE,
					"fontname" : "Tahoma:14b",
					"horizontal_align" : "center",
					"text_horizontal_align" : "center",
				},
				{
					"name" : "average_price_text_ui",
					"type" : "text",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16,
					"text" : "",
					"fontname" : "Tahoma:14b",
					"horizontal_align" : "center",
					"text_horizontal_align" : "center",
				},
				{
					"name" : "split_bar1_ui",
					"type" : "expanded_image",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 25,
					"image" : IMG_PATH + "bar.png",
					"horizontal_align" : "center",
				},
				{
					"name" : "desc_text_ui",
					"type" : "text",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 37,
					"text" : "",
					"fontname" : "Tahoma:14b",
					"horizontal_align" : "center",
					"text_horizontal_align" : "center",
				},
				{
					"name" : "input_bg_ui",
					"type" : "expanded_image",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20,
					"image" : IMG_PATH + "yang_bg.png",
					"horizontal_align" : "center",
					"children" :
					(
						{
							"name" : "input_value_ui",
							"type" : "editline",
							"x" : 25,
							"y" : 6,
							"width" : 158,
							"height" : 19,
							"input_limit" : 12,
							#"only_number" : 1,
							"horizontal_align" : "center",
						},
					),
				},
				{
					"name" : "bg_avg_option_ui",
					"type" : "window",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20 + 34,
					"width" : 187,
					"height" : 18,
					"horizontal_align" : "center",
					"children" :
					(
						{
							"name" : "bg_avg_button_ui",
							"type" : "toggle_button",
							"x" : 0,
							"y" : 0,
							"default_image" : IMG_PATH + "checkbox_new_unselected.tga",
							"over_image" : IMG_PATH + "checkbox_new_selected.tga",
							"down_image" : IMG_PATH + "checkbox_new_selected.tga",
						},
						{
							"name" : "bg_avg_desc_ui",
							"type" : "text",
							"x" : 20,
							"y" : 1,
							"text" : localeInfo.PRICEINPUT_DLG_DESC3,
						},
					),
				},
				{
					"name" : "split_bar2_ui",
					"type" : "expanded_image",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20 + 34 + 26,
					"image" : IMG_PATH + "bar.png",
					"horizontal_align" : "center",
				},
				{
					"name" : "final_price_title_ui",
					"type" : "text",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20 + 34 + 26 + 13,
					"text" : localeInfo.PRICEINPUT_DLG_CHOOSE_PRICE,
					"fontname" : "Tahoma:14b",
					"horizontal_align" : "center",
					"text_horizontal_align" : "center",
				},
				{
					"name" : "final_price_value_ui",
					"type" : "text",
					"x" : 0,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20 + 34 + 26 + 13 + 16,
					"text" : "",
					"fontname" : "Tahoma:14b",
					"horizontal_align" : "center",
					"text_horizontal_align" : "center",
				},
				{
					"name" : "accept_button_ui",
					"type" : "button",
					"x" : -54,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20 + 34 + 26 + 13 + 16 + 25,
					"horizontal_align" : "center",
					"text" : localeInfo.PRICEINPUT_DLG_ACCEPT,
					"default_image" : IMG_PATH + "btn_normal.png",
					"over_image" : IMG_PATH + "btn_hover.png",
					"down_image" : IMG_PATH + "btn_down.png",
				},
				{
					"name" : "cancel_button_ui",
					"type" : "button",
					"x" : 50,
					"y" : 24 + 20 + 110 + 5 + 16 + 37 + 20 + 34 + 26 + 13 + 16 + 25,
					"horizontal_align" : "center",
					"text" : localeInfo.PRICEINPUT_DLG_CLOSE,
					"default_image" : IMG_PATH + "btn_normal.png",
					"over_image" : IMG_PATH + "btn_hover.png",
					"down_image" : IMG_PATH + "btn_down.png",
				},
			),
		},
	),
}
